import { Portal } from "./portal-types";

export const portals: Portal[] = [
  {
    name: "maxio",
    url: "https://developers.maxio.com/http/getting-started/overview",
    logoUrl: "https://img.logo.dev/www.maxio.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for Maxio",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/maxio.webp",
  },
  {
    name: "fortis",
    url: "https://docs.fortis.tech/v/1_0_0.html#/rest/quick-start-guide/overview",
    logoUrl: "https://img.logo.dev/www.fortis-technologies.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for Fortis",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Fortis+API+Portal",
  },
  {
    name: "foxit-esign",
    url: "https://developers.foxitesign.foxit.com/v/1_0_0#/rest/installation-guidelines",
    logoUrl: "https://img.logo.dev/www.foxit.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for Foxit Esign",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/foxit-esign.webp",
  },
  {
    name: "greenbyte",
    url: "https://developer.greenbyte.com/v/2_2-beta#/http",
    logoUrl: "https://img.logo.dev/www.powerfactors.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for Greenbyte",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/greenbyte.webp",
  },
  {
    name: "shell",
    url: "https://developer.shell.com/product-catalog/shell-digital-payments/sdk#/http/setting-up-sdks",
    logoUrl: "https://img.logo.dev/www.shell.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for Shell",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/shell.webp",
  },
  {
    name: "verizon",
    url: "https://thingspace.verizon.com/documentation/api-documentation.html#/http/quick-start/introduction-to-the-verizon-api",
    logoUrl: "https://img.logo.dev/www.thingspace.verizon.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for Verizon Thingspace",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/verizon.webp",
  },
  {
    name: "boku",
    url: "https://developer.boku.com/xml/index.html#/http",
    logoUrl: "https://img.logo.dev/www.boku.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for Boku",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/boku.webp",
  },
  {
    name: "mindbody-online",
    url: "https://developers.mindbodyonline.com/ui/documentation/public-api",
    logoUrl: "https://img.logo.dev/www.mindbodyonline.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for Mindbody Online",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/mindbody-online.webp",
  },
  {
    name: "juniper-mist",
    url: "https://www.juniper.net/documentation/us/en/software/mist/api/http/getting-started/how-to-get-started",
    logoUrl: "https://img.logo.dev/www.juniper.net?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for Juniper Mist",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/juniper-mist.webp",
  },
  {
    name: "postnl",
    url: "https://developer.postnl.nl/docs/#/python/getting-started/how-to-get-started",
    logoUrl: "https://img.logo.dev/www.postnl.nl/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for PostNL",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Postnl+API+Portal",
  },
  {
    name: "apcopay",
    url: "https://apcopayapi.apimatic.dev/v/1_0#/http/introduction/introduction",
    logoUrl: "https://img.logo.dev/www.apcopay.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for Apcopay",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/apcopay.webp",
  },
  {
    name: "akahu",
    url: "https://apimatic-akahu.web.app",
    logoUrl: "https://img.logo.dev/www.akahu.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for akahu",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Akahu+API+Portal",
  },
  {
    name: "hipay",
    url: "http://hipay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.hipay.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for hipay",
    category: "Fintech",
    status: "HAND CURATED",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/hipay.webp",
  },
  {
    name: "worldline",
    url: "http://worldline-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.worldline.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for worldline",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/worldline.webp",
  },
  {
    name: "ramp",
    url: "http://ramp-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ramp.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ramp",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/ramp.webp",
  },
  {
    name: "sumup",
    url: "http://sumup-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.sumup.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for sumup",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Sumup+API+Portal",
  },
  {
    name: "revolut",
    url: "http://revolut-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.revolut.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for revolut",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Revolut+API+Portal",
  },
  {
    name: "payrix",
    url: "http://payrix-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payrix.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for payrix",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/payrix.webp",
  },
  {
    name: "payroc",
    url: "http://payroc-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payroc.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for payroc",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/payroc.webp",
  },
  {
    name: "nium",
    url: "http://nium-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.nium.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for nium",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/nium.webp",
  },
  {
    name: "pxp-solutions",
    url: "http://pxp-solutions-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.pxp-solutions.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for pxp-solutions",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/pxp-solutions.webp",
  },
  {
    name: "ppro",
    url: "http://ppro-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ppro.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ppro",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/ppro.webp",
  },
  {
    name: "paylocity",
    url: "http://paylocity-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paylocity.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paylocity",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/paylocity.webp",
  },
  {
    name: "payoneer",
    url: "http://payoneer-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payoneer.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for payoneer",
    category: "Fintech",
    status: "FEATURED",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/payoneer.webp",
  },
  {
    name: "moneyhub",
    url: "http://moneyhub-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.moneyhub.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for moneyhub",
    category: "Fintech",
    status: "POPULAR",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/moneyhub.webp",
  },
  {
    name: "n26",
    url: "http://n26-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.n26.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for n26",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/n26.webp",
  },
  {
    name: "modular",
    url: "http://modular-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.modulrfinance.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for modular",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/modular.webp",
  },
  {
    name: "merchante",
    url: "http://merchante-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.merchante.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for merchante",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/merchante.webp",
  },
  {
    name: "mastercard",
    url: "http://mastercard-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mastercard.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mastercard",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Mastercard+API+Portal",
  },
  {
    name: "jp-morgan-chase",
    url: "http://jp-morgan-chase-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.jpmorganchase.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for jp-morgan-chase",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/jp-morgan-chase.webp",
  },
  {
    name: "klarna-apis",
    url: "http://klarna-apis-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.klarna.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for klarna-apis",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Klarna-apis+API+Portal",
  },
  {
    name: "coinbase",
    url: "http://coinbase-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.coinbase.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for coinbase",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Coinbase+API+Portal",
  },
  {
    name: "fiserv",
    url: "http://fiserv-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.fiserv.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for fiserv",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/fiserv.webp",
  },
  {
    name: "conekta",
    url: "http://conekta-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.conekta.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for conekta",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/conekta.webp",
  },
  {
    name: "dwolla",
    url: "http://dwolla-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.dwolla.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for dwolla",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/dwolla.webp",
  },
  {
    name: "galileo-ft",
    url: "http://galileo-ft-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.galileo-ft.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for galileo-ft",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/galileo-ft.webp",
  },
  {
    name: "elavon",
    url: "http://elavon-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.elavon.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for elavon",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/elavon.webp",
  },
  {
    name: "cybersource",
    url: "http://cybersource-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.cybersource.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for cybersource",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Cybersource+API+Portal",
  },
  {
    name: "celcoin",
    url: "http://celcoin-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.celcoin.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for celcoin",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/celcoin.webp",
  },
  {
    name: "clip",
    url: "http://clip-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payclip.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for clip",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/clip.webp",
  },
  {
    name: "adyen",
    url: "http://adyen-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payadyen.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for adyen",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Adyen+API+Portal",
  },
  {
    name: "bolt",
    url: "http://bolt-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paybolt.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bolt",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Bolt+API+Portal",
  },
  {
    name: "brex",
    url: "http://brex-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paybrex.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for brex",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Brex+API+Portal",
  },
  {
    name: "marqeta",
    url: "http://marqeta-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.marqeta.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for marqeta",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/marqeta.webp",
  },
  {
    name: "form3",
    url: "http://form3-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.form3.tech?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for form3",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/form3.webp",
  },
  {
    name: "ccbill",
    url: "http://ccbill-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ccbill.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ccbill",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/ccbill.webp",
  },
  {
    name: "izettle",
    url: "http://izettle-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.izettle.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for izettle",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/izettle.webp",
  },
  {
    name: "paysafe",
    url: "http://paysafe-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paysafe.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paysafe",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/paysafe.webp",
  },
  {
    name: "banksapi",
    url: "http://banksapi-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.banksapi.de?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for banksapi",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/banksapi.webp",
  },
  {
    name: "basiq",
    url: "http://basiq-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.basiq.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for basiq",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/basiq.webp",
  },
  {
    name: "ayoconnect",
    url: "http://ayoconnect-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ayoconnect.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ayoconnect",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/ayoconnect.webp",
  },
  {
    name: "banqware",
    url: "http://banqware-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.banqware.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for banqware",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/banqware.webp",
  },
  {
    name: "akurateco",
    url: "http://akurateco-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.akurateco.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for akurateco",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/akurateco.webp",
  },
  {
    name: "arcopay",
    url: "http://arcopay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.arcopay.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for arcopay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/arcopay.webp",
  },
  {
    name: "afterbanks",
    url: "http://afterbanks-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.afterbanks.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for afterbanks",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/afterbanks.webp",
  },
  {
    name: "rapyd",
    url: "http://rapyd-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.rapyd.net?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for rapyd",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Rapyd+API+Portal",
  },
  {
    name: "yapily",
    url: "http://yapily-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.yapily.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for yapily",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/yapily.webp",
  },
  {
    name: "wyre",
    url: "http://wyre-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.sendwyre.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for wyre",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Wyre+API+Portal",
  },
  {
    name: "tyro-payments",
    url: "http://tyro-payments-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.tyro.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for tyro-payments",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/tyro-payments.webp",
  },
  {
    name: "xsolla",
    url: "http://xsolla-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.xsolla.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for xsolla",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/xsolla.webp",
  },
  {
    name: "schufa-holding",
    url: "http://schufa-holding-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.schufa.de?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for schufa-holding",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Schufa-holding+API+Portal",
  },
  {
    name: "verifone",
    url: "http://verifone-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.verifone.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for verifone",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/verifone.webp",
  },
  {
    name: "siliconvalleybank",
    url: "http://siliconvalleybank-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.svb.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for siliconvalleybank",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Siliconvalleybank+API+Portal",
  },
  {
    name: "ebanx",
    url: "http://ebanx-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ebanx.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ebanx",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/ebanx.webp",
  },
  {
    name: "zolando",
    url: "http://zolando-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.zolando.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for zolando",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Zolando+API+Portal",
  },
  {
    name: "mollie",
    url: "http://mollie-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mollie.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mollie",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/mollie.webp",
  },
  {
    name: "zip-co",
    url: "http://zip-co-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.zip.co?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for zip-co",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Zip-co+API+Portal",
  },
  {
    name: "zai",
    url: "http://zai-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.hellozai.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for zai",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/zai.webp",
  },
  {
    name: "tink",
    url: "http://tink-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.tink.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for tink",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/tink.webp",
  },
  {
    name: "mone",
    url: "http://mone-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mone.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mone",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/mone.webp",
  },
  {
    name: "lukka",
    url: "http://lukka-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.lukka.tech?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for lukka",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/lukka.webp",
  },
  {
    name: "moonpay",
    url: "http://moonpay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.moonpay.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for moonpay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/moonpay.webp",
  },
  {
    name: "gusto",
    url: "http://gusto-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.gusto.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for gusto",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Gusto+API+Portal",
  },
  {
    name: "injective",
    url: "http://injective-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.injective.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for injective",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/injective.webp",
  },
  {
    name: "mercury",
    url: "http://mercury-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mercury.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mercury",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/mercury.webp",
  },
  {
    name: "homelight",
    url: "http://homelight-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.homelight.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for homelight",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/homelight.webp",
  },
  {
    name: "mambu",
    url: "http://mambu-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mambu.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mambu",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/mambu.webp",
  },
  {
    name: "lunar",
    url: "http://lunar-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.lunar.app?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for lunar",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/lunar.webp",
  },
  {
    name: "ledger",
    url: "http://ledger-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ledger.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ledger",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/ledger.webp",
  },
  {
    name: "kraken",
    url: "http://kraken-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.kraken.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for kraken",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/kraken.webp",
  },
  {
    name: "uniswap",
    url: "http://uniswap-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.uniswap.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for uniswap",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/uniswap.webp",
  },
  {
    name: "trulioo",
    url: "http://trulioo-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.trulioo.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for trulioo",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/trulioo.webp",
  },
  {
    name: "avant",
    url: "http://avant-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.avant.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for avant",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/avant.webp",
  },
  {
    name: "circle",
    url: "http://circle-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.circle.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for circle",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Circle+API+Portal",
  },
  {
    name: "addepar",
    url: "http://addepar-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.addepar.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for addepar",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Addepar+API+Portal",
  },
  {
    name: "carta",
    url: "http://carta-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.carta.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for carta",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/carta.webp",
  },
  {
    name: "coinlist",
    url: "http://coinlist-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.coinlist.co?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for coinlist",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/coinlist.webp",
  },
  {
    name: "chippercash",
    url: "http://chippercash-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.chippercash.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for chippercash",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/chippercash.webp",
  },
  {
    name: "clearstreet",
    url: "http://clearstreet-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.clearstreet.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for clearstreet",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/clearstreet.webp",
  },
  {
    name: "blockchain",
    url: "http://blockchain-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.blockchain.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for blockchain",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/blockchain.webp",
  },
  {
    name: "openpayd",
    url: "http://openpayd-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.openpayd.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for openpayd",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/openpayd.webp",
  },
  {
    name: "crosskey",
    url: "http://crosskey-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.crosskey.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for crosskey",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/crosskey.webp",
  },
  {
    name: "dapi",
    url: "http://dapi-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.dapi.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for dapi",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/dapi.webp",
  },
  {
    name: "mondu",
    url: "http://mondu-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mondu.ai?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mondu",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/mondu.webp",
  },
  {
    name: "paynova",
    url: "http://paynova-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paynova.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paynova",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/paynova.webp",
  },
  {
    name: "crezco",
    url: "http://crezco-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.crezco.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for crezco",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/crezco.webp",
  },
  {
    name: "codat",
    url: "http://codat-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.codat.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for codat",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Codat+API+Portal",
  },
  {
    name: "belvo",
    url: "http://belvo-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.belvo.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for belvo",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/belvo.webp",
  },
  {
    name: "akoya",
    url: "http://akoya-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.akoya.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for akoya",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/akoya.webp",
  },
  {
    name: "mx",
    url: "http://mx-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mx.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mx",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/mx.webp",
  },
  {
    name: "figo",
    url: "http://figo-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.figopayment.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for figo",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/figo.webp",
  },
  {
    name: "bud",
    url: "http://bud-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.thisisbud.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bud",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/bud.webp",
  },
  {
    name: "bunq",
    url: "http://bunq-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.bunq.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bunq",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/bunq.webp",
  },
  {
    name: "fireblocks",
    url: "http://fireblocks-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.fireblocks.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for fireblocks",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/fireblocks.webp",
  },
  {
    name: "floqast",
    url: "http://floqast-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.floqast.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for floqast",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/floqast.webp",
  },
  {
    name: "flutterwave",
    url: "http://flutterwave-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.flutterwave.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for flutterwave",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/flutterwave.webp",
  },
  {
    name: "figment",
    url: "http://figment-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.figment.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for figment",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/figment.webp",
  },
  {
    name: "flow",
    url: "http://flow-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.flow.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for flow",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/flow.webp",
  },
  {
    name: "truelayer",
    url: "http://truelayer-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.truelayer.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for truelayer",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/truelayer.webp",
  },
  {
    name: "the-bank-of-london",
    url: "http://the-bank-of-london-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.thebankoflondon.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for the-bank-of-london",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/the-bank-of-london.webp",
  },
  {
    name: "teya",
    url: "http://teya-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.teya.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for teya",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/teya.webp",
  },
  {
    name: "paxos",
    url: "http://paxos-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paxos.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paxos",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/paxos.webp",
  },
  {
    name: "symphony",
    url: "http://symphony-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.symphony.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for symphony",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/symphony.webp",
  },
  {
    name: "snapdocs",
    url: "http://snapdocs-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.snapdocs.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for snapdocs",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/snapdocs.webp",
  },
  {
    name: "neon",
    url: "http://neon-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.neon.tech?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for neon",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/neon.webp",
  },
  {
    name: "paystand",
    url: "http://paystand-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paystand.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paystand",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/paystand.webp",
  },
  {
    name: "taxbit",
    url: "http://taxbit-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.taxbit.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for taxbit",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/taxbit.webp",
  },
  {
    name: "solaris",
    url: "http://solaris-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.solaris.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for solaris",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/solaris.webp",
  },
  {
    name: "kudosity",
    url: "http://kudosity-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.kudosity.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for kudosity",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/kudosity.webp",
  },
  {
    name: "inxpress",
    url: "http://inxpress-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.inxpress.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for inxpress",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/inxpress.webp",
  },
  {
    name: "clickatell",
    url: "http://clickatell-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.clickatell.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for clickatell",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/clickatell.webp",
  },
  {
    name: "fastspring",
    url: "http://fastspring-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.fastspring.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for fastspring",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/fastspring.webp",
  },
  {
    name: "global-freight-solutions",
    url: "http://global-freight-solutions-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.gfsdeliver.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for global-freight-solutions",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/global-freight-solutions.webp",
  },
  {
    name: "bandwidth",
    url: "http://bandwidth-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.bandwidth.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bandwidth",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/bandwidth.webp",
  },
  {
    name: "heymarket",
    url: "http://heymarket-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.heymarket.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for heymarket",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/heymarket.webp",
  },
  {
    name: "bambora",
    url: "http://bambora-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.bambora.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bambora",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/bambora.webp",
  },
  {
    name: "truelayer",
    url: "http://truelayer-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.truelayer.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for truelayer",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/truelayer.webp",
  },
  {
    name: "dojo",
    url: "http://dojo-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.dojo.tech?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for dojo",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/dojo.webp",
  },
  {
    name: "keybank",
    url: "http://keybank-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.keybank.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for keybank",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/keybank.webp",
  },
  {
    name: "luminor",
    url: "http://luminor-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.luminor.lt?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for luminor",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/luminor.webp",
  },
  {
    name: "finix",
    url: "http://finix-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.finix.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for finix",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "/assets/banners/finix.webp",
  },
  {
    name: "fnz-group",
    url: "http://fnz-group-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.fnz-group.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for fnz-group",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Fnz-group+API+Portal",
  },
  {
    name: "jumio",
    url: "http://jumio-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.jumio.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for jumio",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Jumio+API+Portal",
  },
  {
    name: "great-american-insurance",
    url: "http://great-american-insurance-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.greatamericaninsurancegroup.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for great-american-insurance",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Great-american-insurance+API+Portal",
  },
  {
    name: "corpay",
    url: "http://corpay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.corpay.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for corpay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Corpay+API+Portal",
  },
  {
    name: "deutsche-bank",
    url: "http://deutsche-bank-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.deutsche-bank.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for deutsche-bank",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Deutsche-bank+API+Portal",
  },
  {
    name: "common-wealth-bank",
    url: "http://common-wealth-bank-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.commbank.com.au?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for common-wealth-bank",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Common-wealth-bank+API+Portal",
  },
  {
    name: "check",
    url: "http://check-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.checkhq.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for check",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Check+API+Portal",
  },
  {
    name: "dnb",
    url: "http://dnb-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.dnb.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for dnb",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Dnb+API+Portal",
  },
  {
    name: "bakkt",
    url: "http://bakkt-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.bakkt.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bakkt",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Bakkt+API+Portal",
  },
  {
    name: "experian",
    url: "http://experian-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.experian.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for experian",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Experian+API+Portal",
  },
  {
    name: "chubb",
    url: "http://chubb-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.chubb.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for chubb",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Chubb+API+Portal",
  },
  {
    name: "bnp-paribas",
    url: "http://bnp-paribas-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.group.bnpparibas?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bnp-paribas",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Bnp-paribas+API+Portal",
  },
  {
    name: "dock-tech",
    url: "http://dock-tech-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.dock-tech.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for dock-tech",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Dock-tech+API+Portal",
  },
  {
    name: "cigna",
    url: "http://cigna-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.cigna.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for cigna",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Cigna+API+Portal",
  },
  {
    name: "nab",
    url: "http://nab-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.nab.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for nab",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Nab+API+Portal",
  },
  {
    name: "north-american-bancard",
    url: "http://north-american-bancard-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.north.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for north-american-bancard",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=North-american-bancard+API+Portal",
  },
  {
    name: "railsr",
    url: "http://railsr-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.railsr.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for railsr",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Railsr+API+Portal",
  },
  {
    name: "satispay",
    url: "http://satispay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.satispay.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for satispay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Satispay+API+Portal",
  },
  {
    name: "payfit",
    url: "http://payfit-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payfit.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for payfit",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Payfit+API+Portal",
  },
  {
    name: "sovos",
    url: "http://sovos-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.sovos.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for sovos",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Sovos+API+Portal",
  },
  {
    name: "rootplatform",
    url: "http://rootplatform-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.rootplatform.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for rootplatform",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Rootplatform+API+Portal",
  },
  {
    name: "scalapay",
    url: "http://scalapay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.scalapay.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for scalapay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Scalapay+API+Portal",
  },
  {
    name: "orum",
    url: "http://orum-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.orum.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for orum",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Orum+API+Portal",
  },
  {
    name: "santander-uk",
    url: "http://santander-uk-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.santander.co.uk?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for santander-uk",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Santander-uk+API+Portal",
  },
  {
    name: "opensea",
    url: "http://opensea-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.opensea.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for opensea",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Opensea+API+Portal",
  },
  {
    name: "sagesure",
    url: "http://sagesure-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.sagesure.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for sagesure",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Sagesure+API+Portal",
  },
  {
    name: "solid",
    url: "http://solid-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.solidifi.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for solid",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Solid+API+Portal",
  },
  {
    name: "paymob",
    url: "http://paymob-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paymob.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paymob",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Paymob+API+Portal",
  },
  {
    name: "sila",
    url: "http://sila-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.silamoney.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for sila",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Sila+API+Portal",
  },
  {
    name: "treasure-data",
    url: "http://treasure-data-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.treasuredata.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for treasure-data",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Treasure-data+API+Portal",
  },
  {
    name: "token",
    url: "http://token-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.token.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for token",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Token+API+Portal",
  },
  {
    name: "toast",
    url: "http://toast-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.pos.toasttab.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for toast",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Toast+API+Portal",
  },
  {
    name: "veem",
    url: "http://veem-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.veem.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for veem",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Veem+API+Portal",
  },
  {
    name: "vipps-mobilepay",
    url: "http://vipps-mobilepay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.vipps.no?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for vipps-mobilepay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Vipps-mobilepay+API+Portal",
  },
  {
    name: "sumsub",
    url: "http://sumsub-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.sumsub.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for sumsub",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Sumsub+API+Portal",
  },
  {
    name: "western-union",
    url: "http://western-union-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.westernunion.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for western-union",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Western-union+API+Portal",
  },
  {
    name: "zeta-tech",
    url: "http://zeta-tech-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.zeta-tech.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for zeta-tech",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Zeta-tech+API+Portal",
  },
]