openapi: 3.0.1
info:
  title: na.internal.analytics.stripe.1
  description: 'A sample API with information related to a technical conference.  The available resources  include *Speakers*, *Sessions* and *Topics*.  A single write operation is available to provide  feedback on a session.'
  version: '1'
servers:
  - url: https://nauat08.chubbdigital.com/analytics.billing.stripe
  - url: https://nauat.chubbdigital.com/analytics.billing.stripe
  - url: https://dp-uat.digitalgateway.chubb.com/analytics.billing.stripe
  - url: https://mtls-uat.na.digitalgateway.chubb.com/analytics.billing.stripe
  - url: https://na-central-uat.chubbdigital.com/analytics.billing.stripe
paths:
  /mock:
    get:
      tags:
        - Discovery
        - Demo
      summary: mock
      description: Mocking test
      operationId: mock
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /caching:
    get:
      tags:
        - Demo
      summary: caching
      description: Caching test
      operationId: caching
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /routing:
    get:
      tags:
        - Demo
      summary: routing
      description: Routing test
      operationId: routing
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /encrypt:
    post:
      tags:
        - Demo
      summary: encrypt
      description: encrypt test
      operationId: encrypt
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /decrypt:
    post:
      tags:
        - Demo
      summary: decrypt
      description: decrypt test
      operationId: decrypt
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /payloadTrans:
    put:
      tags:
        - Demo
      summary: payloadTrans
      description: PayloadTransformation test
      operationId: payloadTrans
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitSessionBodyRequest-json'
            example: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
components:
  schemas:
    SubmitSessionBodyRequest-json:
      type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]