openapi: 3.0.0
info:
  title: Kraken REST API
  description: API for interacting with Kraken's trading platform, including account balance, trades, and orders.
  version: 1.0.0
servers:
  - url: https://api.kraken.com
    description: Kraken API Server

paths:
  /0/private/TradeBalance:
    post:
      summary: Get trade balance
      operationId: getTradeBalance
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                asset:
                  type: string
                  description: Base asset to use for the trade balance
                  example: ZUSD
                nonce:
                  type: string
                  description: Unique nonce used for the request
                  example: "1616492376594"
      responses:
        '200':
          description: Trade balance retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      eb:
                        type: string
                        example: "1000.1234"
                      tb:
                        type: string
                        example: "1000.1234"
                      m:
                        type: string
                        example: "0.0000"
                      n:
                        type: string
                        example: "1000.1234"
                      c:
                        type: string
                        example: "0.0000"
                      v:
                        type: string
                        example: "0.0000"
                      e:
                        type: string
                        example: "0.0000"
                      mf:
                        type: string
                        example: "0.0000"
                      ml:
                        type: string
                        example: "0.0000"
        '400':
          description: Invalid request
        '401':
          description: Unauthorized

  /0/private/Balance:
    post:
      summary: Get account balance
      operationId: getBalance
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                nonce:
                  type: string
                  description: Unique nonce used for the request
                  example: "1616492376594"
      responses:
        '200':
          description: Account balance retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    additionalProperties:
                      type: string
                      example: "0.12345678"
        '400':
          description: Invalid request
        '401':
          description: Unauthorized

  /0/private/OpenOrders:
    post:
      summary: Get open orders
      operationId: getOpenOrders
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                nonce:
                  type: string
                  description: Unique nonce used for the request
                  example: "1616492376594"
                trades:
                  type: boolean
                  description: Include trades in output
                  example: true
      responses:
        '200':
          description: Open orders retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      open:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            refid:
                              type: string
                            userref:
                              type: string
                            status:
                              type: string
                            opentm:
                              type: number
                            starttm:
                              type: number
                            expiretm:
                              type: number
                            descr:
                              type: object
                              properties:
                                pair:
                                  type: string
                                type:
                                  type: string
                                ordertype:
                                  type: string
                                price:
                                  type: string
                                price2:
                                  type: string
                                leverage:
                                  type: string
                                order:
                                  type: string
                                close:
                                  type: string
                            vol:
                              type: string
                            vol_exec:
                              type: string
                            cost:
                              type: string
                            fee:
                              type: string
                            price:
                              type: string
                            stopprice:
                              type: string
                            limitprice:
                              type: string
                            misc:
                              type: string
                            oflags:
                              type: string
                            trades:
                              type: array
                              items:
                                type: string
        '400':
          description: Invalid request
        '401':
          description: Unauthorized

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: API-Key
    ApiSignAuth:
      type: apiKey
      in: header
      name: API-Sign

security:
  - ApiKeyAuth: []
  - ApiSignAuth: []
