openapi: "3.0.0"
info:
  version: "3.0.1"
  title: "Partner Dispatch Service"
  x-api-id: "7867f8da-0de6-4f65-886c-bc838119f693"
  x-audience: external-partner
  description: |
    The Partner Dispatch Service is part of ZEOS Fulfillment enabling Zalando partners (merchants) to store their own stocks in Zalando Warehouses
    and fulfill orders from these stocks.

    This API implements the part of the workflow where a partner or partner integrator sends shipping notices
    for concrete product items and quantities to be scheduled for shipping to a specific Zalando warehouse at a given point in time
    and to be supported and observed by ZFS service operations team.


    ## API workflow

    To get a better overview in the following the typical API workflow is shown.
    Please note that this diagram does not cover the complete process with all its possible branches but should depict
    the typical flow beginning with a merchant creating a shipping notice until the Zalando warehouse being ready to receive the shipment:

    [Diagram Flow](../../../zfs/shipping-notices/assets/shipping-notices-api-compact-flow.png)


    ## Resource Types

    ### Shipping Notice

    A shipping notice captures any base information required from a merchant to notify Zalando about pending deliveries in advance.

    ### Announced Item Set

    An announced item set lists the items and quantities planned to be shipped by a merchant as part of a shipping-notice.

    ### Announcement Confirmation

    This is a confirmation by the merchant to indicate that there will be no more changes done to the Shipping Notice resource
    and that the newest Announced Item Set is also final to continue with the workflow to request a delivery date.

    ### Dispatch Item Set

    A dispatch item set lists the items and quantities handed over to the carrier by the merchant as part of a shipping-notice.

    ### Dispatch Confirmation

    This is a confirmation by the merchant to indicate that there will be no more changes done to the item set to be dispatched.
    This is required to be able to continue with the workflow to create an inbound tour.

    ### Tour

    Represents a warehouse tour and its current status.

    ## Conflict Handling

    Any endpoint supporting HTTP PUT or HTTP POST method makes use of `ETag` and `If-Match` HTTP headers to detect collisions when two actors try to change a resource concurrently.

    For further explanation see also: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

    Every GET request for a shipping-notice or any subresource of a shipping-notice will return an `ETag` determining the current shipping-notice version.

    With every `PUT` attempting to change an existing resource the actor needs to send the `If-Match` header containing the recent `ETag` of the shipping-notice. Only by fulfilling this requirement the `PUT` request will be accepted.

    With every POST attempting to create a subresource of a shipping-notice the actor needs to send the `If-Match` header containing the recent `ETag` of the shipping-notice. This action will update the `ETag` of the shipping-notice resource. Only by fulfilling this requirement the `POST` request will be accepted.

    If the `If-Match` header does not contain the recent `ETag` of the resource then an error is returned with HTTP status code 412 (Precondition Failed).
    If the `If-Match` header is omitted when attempting to change an existing resource then an error is returned with HTTP status code 428 (Precondition Required).

    There is only one `ETag` for the entire shipping-notice resource including all sub resources to enforce consistent versioning for all items of a shipping-notice. This is to prevent that separate items of a shipping-notice (for example an announced item set or a delivery date request) are created in parallel possibly leading to an unexpected or inconsistent result.

    ## Pagination

    HTTP GET requests querying resources to be returned as result set implement pagination. In this case a result set containg a list of result `items` and additionally an optional `next` href pointing to the next page of the query result.

servers:
  - url: 'https://api.merchants.zalando.com/zfs'
    description: Production instance
  - url: 'https://api-sandbox.merchants.zalando.com/zfs'
    description: Sandbox instance for merchant center

paths:
  '/shipping-notices':
    get:
      description: |
        Returns a paginated query result containing a list of shipping-notices matching the given query ordered by creation time in descending order.
        This endpoint is required by ZFS Service Operations to get an overview about shipping notices to be processed and to track progress.
        It can also be used by merchants to get access all his/her shipping-notice data.
      security:
        - oauth2: [ zfs-advice-service.shipping-notice.read ]
      tags:
        - Shipping Notice
    post:
      description: |
        Creates a shipping-notice.

        When creating a new shipping-notice a `zalando_advice_id` will be generated synchronously
        which is the Zalando specific ID to identify a shipping notice during its lifecycle.

        The shipping notice resource uuid will also be generated during creation which is a uniquely identification for the resource.

        Preconditions:
        - requesting actor is authorized to access the shipping-notice-id

        Postconditions:
        - the shipping-notice state is set to "initial"

      security:
        - oauth2: [ zfs-advice-service.shipping-notice.write ]
      tags:
        - Shipping Notice
  '/shipping-notices/{shipping-notice-id}':
    get:
      description: |
        Returns shipping-notice resource for a given shipping-notice ID.
        Used by a merchant and by ZFS Service operations to track the status of a shipping-notice currently in progress.

        Preconditions:
        - requesting actor is authorized to access the shipping-notice-id

      security:
        - oauth2: [ zfs-advice-service.shipping-notice.read ]
      tags:
        - Shipping Notice
    put:
      description: |
        Updates an existing shipping-notice
        Used by merchants to update general shipping notice

        Note:
        As a temporary measure for backwards compatibility, this endpoint also supports creating new shipping notices with a given ID by the author.
        However, this behavior will be deprecated once the new POST endpoint for creation is fully rolled out.

        Preconditions:
        - requesting actor is authorized to access the shipping-notice-id
        - shipping-notice resource is in status `initial`

        Postconditions:
        - the shipping-notice state is set to "initial"

      security:
        - oauth2: [ zfs-advice-service.shipping-notice.write ]
      tags:
        - Shipping Notice
  '/shipping-notices/{shipping-notice-id}/announced-item-sets':
    get:
      description: |
        Returns a paginated query result containing a list of announced item sets for a given shipping-notice ID ordered by creation time in descending order.
        Used by ZFS Service operations to track the validation status of items. Can also be used by the merchant to access its item sets.

        Preconditions:
        - requesting actor is authorized to access the shipping-notice-id

      security:
        - oauth2: [ zfs-advice-service.shipping-notice.read ]
      tags:
        - Item Set
    post:
      description: |
        Creates a new announced-item-set for a given shipping-notice ID. An announced-item-set resource is immutable.
        Used by merchants to specify either each product item and its planned quantity to be shipped to a Zalando warehouse, or to provide only the total quantity of items. 

        An announced-item-set is validated synchronously. 
        If individual items are provided, each item in the set is validated to ensure it is valid as per the ShippableItem definition. See definition of ShippableItem for details.

        Preconditions:
        - requesting actor is authorized to access the shipping-notice-id
        - shipping-notice resource is in status `initial`

      security:
        - oauth2: [ zfs-advice-service.shipping-notice.write ]
      tags:
        - Item Set
  '/shipping-notices/{shipping-notice-id}/announced-item-sets/{shippable-item-set-id}':
    get:
      description: |
        Returns announced-item-set resource for a given shipping-notice ID and announced-item-set ID.
        Used by ZFS Service operations to track the validation status of items. Can also be used by the merchant to access its item sets.

        Preconditions:
        - requesting actor is authorized to access the shipping-notice-id

      security:
        - oauth2: [ zfs-advice-service.shipping-notice.read ]
      tags:
        - Item Set
  '/shipping-notices/{shipping-notice-id}/announcement-confirmations':
    post:
      description: |
        Creates an announcement-confirmation for a given shipping-notice ID, which is a
        status transition resource without (body) data to trigger a shipping-notice state change
        from "initial" to "ready_for_delivery_date".
        An announcement-confirmation resource is immutable.
        This endpoint is to be used by merchants to confirm that the shipping-notice and last announced-item-set
        are ready to continue with the workflow to request a delivery date.
        Also at most one announcement-confirmation resource can be created per shipping-notice resource.

        Preconditions:
        - requesting actor is authorized to access the shipping-notice-id
        - shipping-notice resource is in status `initial`
        - the shipping-notice resource must have the following information:

          zalando_merchant_id,
          zalando_advice_id,
          requested_zalando_location_id,
          carrier_name,
          pallets_count,
          colli_count,
          hanging_goods_count,
          earliest_delivery_date,
          contact_email

        - there must be at least one announced-item-set resource and the newest one must have validation state 'succeeded'
        - no announcement confirmation exists yet for the given shipping-notice-id

        Postconditions:
        - the shipping-notice state is implicitly set to `ready_for_delivery_date`

      security:
        - oauth2: [ zfs-advice-service.shipping-notice.write ]
      tags:
        - Booking
  '/shipping-notices/{shipping-notice-id}/dispatch-item-sets':
    get:
      description: |
        Returns a paginated query result containing a list of dispatch-item-sets for a given shipping-notice ID ordered by creation date in descending order.
        Used by ZFS Service operations to track the validation status of items. Can also be used by the merchant to access its item sets.

        Preconditions:
        - requesting actor is authorized to access the shipping-notice-id

      security:
        - oauth2: [ zfs-advice-service.shipping-notice.read ]
      tags:
        - Item Set
    post:
      description: |
        Creates a new dispatch-item-set for a given shipping-notice ID. A dispatch-item-set resource is immutable.
        Used by merchants to define which product items and quantities are dispatched to a Zalando warehouse.

        A dispatch-item-set is validated synchronously by verifying that any item of the set is valid. See definition of ShippableItem for details.

        Preconditions:
        - requesting actor is authorized to access the shipping-notice-id
        - shipping-notice resource is in status `ready_for_dispatch`

      security:
        - oauth2: [ zfs-advice-service.shipping-notice.write ]
      tags:
        - Item Set
  '/shipping-notices/{shipping-notice-id}/dispatch-confirmations':
    post:
      description: |
        Creates a dispatch-confirmation for a given shipping-notice ID, which is a
        status transition resource without (body) data to trigger a shipping-notice state change
        from "ready_for_dispatch" to "ready_for_receive".
        A dispatch-confirmation resource is immutable.

        This endpoint is to be used by merchants to confirm that:

        - either the last dispatch-item-set (if any exists because it is optional)
        - or the last announced-item-set

        are ready to continue with the workflow to request an inbound tour.

        A `shipping-notice` can only have one `dispatch-confirmation`.
        Creating another `dispatch-confirmation` will lead to a conflict.
        It is not possible to upload more `dispatch-item-set`s after a `dispatch-confirmation` was created.

        Preconditions:
        - requesting actor is authorized to access the shipping-notice-id
        - shipping-notice resource is in status `ready_for_dispatch`
        - there must be a delivery-date-confirmation
        - optionally there can be a dispatch-item-set
        - no dispatch-confirmation exists yet for the given shipping-notice-id

        Postconditions:
        - an inbound-tour resource is created
        - the shipping-notice state is implicitily set to `ready_for_receive`

      security:
        - oauth2: [ zfs-advice-service.shipping-notice.write ]
      tags:
        - Booking
  '/tours':
    get:
      description: Returns information about a list of tours belonging to a given Zalando Advice ID.
      security:
        - oauth2: [ zfs-advice-service.tour.read ]
      tags:
        - Tour
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://api-sandbox.merchants.zalando.com/auth/token"
          scopes:
            zfs/shipping-notice/read: Allows for the reading of shipping-notice resources and any subresources.
            zfs/shipping-notice/write: Allows for the creating or updating of shipping-notice resources and any subresources.
            zfs/tour/read: Allows to read tour data
