swagger: "2.0"
info:
  version: "2.2.0"
  title: "Articles Service"
  description: "This specification describes the Articles Service of the Zalando zDirect Platform."
securityDefinitions:
  merchant_platform:
    type: oauth2
    flow: application
    tokenUrl: https://api-sandbox.merchants.zalando.com/auth/token
    scopes:
      articles/stock/write: Access to setting product stocks
      articles/ean/read: Access to looking up Zalando IDs by EAN
schemes:
- "https"
parameters:
  x-flow-id:
    name: X-Flow-Id
    in: header
    description: Unique identifier for the request
    required: false
    type: string
    format: uuid
  Authorization:
    name: "Authorization"
    in: "header"
    required: true
    type: "string"
paths:
  /articles/mappings:
    get:
      deprecated: true
      security:
        - merchant_platform: ["articles/ean/read"]
      summary: "Matches an EAN to an article id (Zalando SKU)"
      produces:
      - "application/vnd.api+json"
      parameters:
      - name: "ean"
        in: "query"
        required: true
        type: "string"
      - $ref: "#/parameters/Authorization"
      - $ref: "#/parameters/x-flow-id"
      responses:
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/ArticleMappingJson"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
  /stocks:
    post:
      deprecated: true
      operationId: updateStocks
      summary: "Update stocks"
      consumes:
      - "application/vnd.api+json"
      produces:
      - "application/vnd.api+json"
      parameters:
      - $ref: "#/parameters/Authorization"
      - $ref: "#/parameters/x-flow-id"
      - in: "body"
        name: "body"
        description: "StockEntityBodyJson"
        required: true
        schema:
          $ref: "#/definitions/StockEntityBodyJson"
      responses:
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/StockEntityJson"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        429:
          description: "Too many requests"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/Error"
          headers:
            X-Flow-Id:
              type: "string"
              description: "Unique identifier for the request"
      security:
      - merchant_platform: ["articles/stock/write"]

definitions:
  StockEntityBodyJson:
    type: "object"
    required:
    - "data"
    properties:
      data:
        $ref: "#/definitions/StockEntity"
    description: "A stock for a given article"
  StockEntityJson:
    type: "object"
    required:
    - "data"
    properties:
      data:
        $ref: "#/definitions/StockEntity"
    description: "A stock for a given article"
  StockEntity:
    type: "object"
    required:
    - "id"
    - "type"
    properties:
      id:
        type: "string"
        description: "Identifier for a stock, formatted as merchantId/salesChannel/articleId"
      type:
        type: "string"
        description: "de.zalando.brand.artmc.api.service.StockEntity"
      attributes:
        type: "object"
        properties:
          article_id:
            type: "string"
          app_domain:
            type: "string"
          merchant_id:
            type: integer
          quantity:
            type: "integer"
            description: "the amount of stock"
        required:
        - "article_id"
        - "app_domain"
        - "merchant_id"
        - "quantity"
  ArticleMapping:
    type: "object"
    required:
    - "id"
    - "type"
    properties:
      id:
        type: "string"
      type:
        type: "string"
        description: "de.zalando.brand.artmc.api.service.ArticleMapping"
      attributes:
        type: "object"
        properties:
          ean:
            type: "string"
          article_id:
            type: "string"
          config_id:
            type: "string"
          model_id:
            type: "string"
        required:
        - "article_id"
        - "config_id"
        - "model_id"
        - "ean"
  Error:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
  ArticleMappingJson:
    type: "object"
    required:
    - "data"
    properties:
      data:
        $ref: "#/definitions/ArticleMapping"
    description: "A mapping from an article sku to an article id"
