openapi: 3.0.0

info:
  title: Product Status Reports API
  description: |
    This service provides up-to-date information about products, such as validation status, current price, and available stock.
  x-audience: external-partner
  version: 1.0.0

servers:
  - url: api.merchants.zalando.com
    description: Production Environment

paths:
  /graphql:
    post:
      summary: Serves all products requests
      security:
        - merchant_platform:
            - Products/products/read
      requestBody:
        description: The requested products filters.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GraphQLRequest"
      responses:
        200:
          description: The requested products result.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GraphQLResponse"

components:
  securitySchemes:
    merchant_platform:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.merchants.zalando.com/auth/token
          scopes:
            Products/products/read: Grant read access to products.

  schemas:
    GraphQLRequest:
      type: object
      description: Paginated request for products.
      required:
        - query
      properties:
        query:
          description: The GraphQL query encoded as a JSON string
          type: string
        variables:
          description: A map of variables passed to the GraphQL operation
          type: object
        operationName:
          description: The top-level GraphQL operation to invoke
          type: string
      example:
        query: "{\n   psr {\n    product_models(input: {\n      merchant_ids: [\"ca4c4022-e254-4af1-a352-e3928067e736\"],\n      status_clusters: [],\n      status_detail_codes: [],\n      season_codes: [],\n      brand_codes: [],\n      country_codes: [],\n      limit: 10,\n      eans: [\"0883212287700\"]\n    }) {\n    items {\n      zalando_product_model_id\n      merchant_product_model_id\n      product_configs {\n        product_simples {\n          ean\n        }\n      }\n    }\n    }\n  }\n}\n"
    
    GraphQLResponse:
      type: object
      properties:
        data:
          type: object
      example:
        data:
          psr:
            product_models:
              items: []
