openapi: "3.0.2"
info:
  title: "Stock Locations API"
  description: |
    ZFS Fulfillment, Return and Inbound Distribution Centers API

    Allows to get Return, Fulfillment and Inbound Distribution Centers of the Zalando Fulfillment Network Regardless of the Relevancy for the Partner

  version: "1.0.0"
  x-api-id: "c7eae9f2-250d-11ec-9621-0242ac130002"
  x-audience: "external-partner"

servers:
  - url: "api.merchants.zalando.com/zfs"
    description: "Production Instance"
  - url: "api-sandbox.merchants.zalando.com/zfs"
    description: "Sandbox Instance for Stock Locations API"

tags:
  - name: StockLocation

paths:
  /stock-locations:
    get:
      summary: Get all Return, Fulfillment and Inbound Distribution Centers of the Zalando Fulfillment Network Regardless of the Relevancy for the Partner
      tags:
        - StockLocation
      security:
        - merchant_platform:
            - "zfs/stock-location/read"
      responses:
        200:
          description: "The Fulfillment, Inbound Distribution and Return Centers"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockLocations'
        default:
          description: An error occurred - see status code and problem object for more information.
          content:
            "application/problem+json":
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
  /stock-locations/{id}:
    get:
      summary: Get a Stock Location by ID
      tags:
        - StockLocation
      security:
        - merchant_platform:
            - "zfs/stock-location/read"
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: Stock Location UUID (Fulfillment, Return or Inbound Distribution Center Id)
      responses:
        200:
          description: "The Fulfillment, Inbound Distribution and Return Centers"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockLocation'
        default:
          description: An error occurred - see status code and problem object for more information.
          content:
            "application/problem+json":
              schema:
                $ref: 'https://opensource.zalando.com/restful-api-guidelines/problem-1.0.1.yaml#/Problem'
components:
  securitySchemes:
    merchant_platform:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://api-sandbox.merchants.zalando.com/auth/token"
          scopes:
            "zfs/stock-location/read": "Grants read access for reading stock locations."
  schemas:
    StockLocations:
      type: object
      description: |
        Array of Stock Locations
      properties:
        stock_locations:
          type: array
          items:
            $ref: '#/components/schemas/StockLocation'
    StockLocation:
      type: object
      description: |
        The Stock Location is either Fulfillment, Inbound Distribution or Return Center.
      properties:
        id:
          type: string
          format: uuid
          description: Stock Location UUID (Fulfillment, Return or Inbound Distribution Center ID)
        capabilities:
          type: array
          items:
            $ref: '#/components/schemas/Capability'
        location:
          $ref: '#/components/schemas/Location'
        type:
          $ref: '#/components/schemas/FacilityType'
        name:
          type: string
          example: Erfurt
          description: Unique Stock Location Name
        abbreviation:
          type: string
          example: EF
          pattern: '[A-Z]{2,3}'
          description: Unique Abbreviation of the Stock Location
        valid_from:
          type: string
          format: date-time
          example: '1996-12-19T16:39:57-08:00'
      required:
        - id
        - name
        - type
    Capability:
      type: string
      x-extensible-enum:
        - "BEAUTY_ITEMS"
        - "BULKY_ITEMS"
        - "CROSS_DOCKING"
        - "DANGEROUS_GOODS"
        - "INBOUND_ITEM"
        - "INBOUND_RELOCATION"
        - "INBOUND_REPLENISHMENT"
        - "INBOUND_RETURN"
        - "INBOUND_SHIPMENT"
        - "OUTBOUND_RELOCATION"
        - "OUTBOUND_REPLENISHMENT"
        - "OUTBOUND_RETURN"
        - "OUTBOUND_SHIPMENT"
        - "PRIORITY_OUTBOUND_SHIPMENT"
        - "SELF_SERVICE"
        - "STORE_ITEM"
      description: |
        BEAUTY_ITEMS: The Facility is capable of physically processing/handling beauty items (e.g. cosmetics).
        BULKY_ITEMS: The Facility is capable of physically processing/handling bulky items (e.g. furniture).
        CROSS_DOCKING: The Facility is capable of performing cross-docking.
        DANGEROUS_GOODS: The Facility is capable of physically processing/handling dangerous items.
        INBOUND_ITEM: The Facility is capable of physically receiving items without processing them further.
        INBOUND_RELOCATION: The Facility is capable of physically receiving relocations without processing them further.
        INBOUND_REPLENISHMENT: The Facility is capable of physically receiving replenishments without processing them further.
        INBOUND_RETURN: The Facility is capable of physically receiving returns without processing them further.
        INBOUND_SHIPMENT: The Facility is capable of physically receiving shipments without processing them further.
        OUTBOUND_RELOCATION: The Facility is capable of physically sending out relocations.
        OUTBOUND_REPLENISHMENT: The Facility is capable of physically sending out replenishments.
        OUTBOUND_RETURN: The Facility is capable of physically sending out returns.
        OUTBOUND_SHIPMENT: The Facility is capable of physically sending out shipments.
        PRIORITY_OUTBOUND_SHIPMENT: The Facility is capable of prioritizing shipments, when sending them out.
        SELF_SERVICE: The Facility is not operated by humans.
        STORE_ITEM: The Facility is capable of physically storing items.
      example:
        "OUTBOUND_SHIPMENT"
    FacilityType:
      type: string
      x-extensible-enum:
        - "INBOUND_DISTRIBUTION_CENTER"
        - "FULFILLMENT_CENTER"
        - "RETURN_CENTER"
      description: |
        the type of the facility based on the capabilities that are owned by the facility.
      example:
        "FULFILLMENT_CENTER"
    Location:
      type: object
      properties:
        name:
          description: |
            Stock location legal name if present
          type: string
          example: Zalando Logistics SE & Co. KG
        postal_code:
          description: |
            zip code or postal code
          type: string
          example: 14265
        country_code:
          type: string
          format: "iso-3166"
          description: Two letter country code as defined in ISO 3166-1 alpha-2
          example:
            "DE"
        street:
          description: |
            the full street address including house number and street name
          type: string
          example: Schönhauser Allee 103
        city:
          description: |
            name of the city / locality
          type: string
          example: Berlin
        latitude:
          type: number
          format: double
          example: 51.1110
        longitude:
          type: number
          format: double
          example: 6.4413
      required:
        - country_code