openapi: 3.0.0
info:
  title: Ledger Vault API
  description: API for interacting with Ledger Vault, including reporting, transactions, and notifications.
  version: 1.0.0
servers:
  - url: https://vault.ledger.com/api
    description: Ledger Vault API Server

paths:
  /accounts:
    get:
      summary: Get all accounts
      operationId: getAccounts
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Successfully retrieved accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "account_id_123"
                    name:
                      type: string
                      example: "Main Vault"
                    balance:
                      type: number
                      example: 100.5
        '401':
          description: Unauthorized

  /transactions:
    get:
      summary: Get all transactions
      operationId: getTransactions
      security:
        - ApiKeyAuth: []
      parameters:
        - name: account_id
          in: query
          required: false
          schema:
            type: string
          description: Filter transactions by account ID
      responses:
        '200':
          description: Successfully retrieved transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "transaction_id_456"
                    status:
                      type: string
                      example: "completed"
                    amount:
                      type: number
                      example: 50.0
                    asset:
                      type: string
                      example: "BTC"
        '401':
          description: Unauthorized

  /notifications:
    get:
      summary: Get all notifications
      operationId: getNotifications
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Successfully retrieved notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "notification_id_789"
                    message:
                      type: string
                      example: "Transaction completed"
                    timestamp:
                      type: string
                      format: date-time
                      example: "2024-09-01T12:34:56Z"
        '401':
          description: Unauthorized

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
