openapi: 3.0.1
info:
  title: na.external.digital-sharedservices.tokens
  description: 'Generate a bearer token using Appid, App Secret and resource to access your APIs'
  version: ''
servers:
  - url: https://nauat08.chubbdigital.com/api/v1/tokens
  - url: https://nauat.chubbdigital.com/api/v1/tokens
  - url: https://dp-uat.digitalgateway.chubb.com/api/v1/tokens
  - url: https://mtls-uat.na.digitalgateway.chubb.com/api/v1/tokens
  - url: https://na-central-uat.chubbdigital.com/api/v1/tokens
paths:
  /:
    post:
      summary: Token
      description: 'Generate and return an Authorization Token, to be used with all subsequent API calls.'
      operationId: token
      parameters:
        - name: App_ID
          in: header
          description: App_ID supplied by CHUBB
          required: true
          schema:
            type: string
        - name: App_Key
          in: header
          description: App_Key supplied by CHUBB
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 
components: { }