openapi: 3.0.1
info:
  title: OPG BIN Details API
  description: Asynchronous API to provide BIN details
  contact:
    name: Payoneer Germany GmbH
    url: https://www.payoneer.com
    email: optilesupport@payoneer.com
  version: "0.5.0"
servers:
  - url: "https://api.{environment}.oscato.com"
    variables:
      environment:
        default: live
        enum:
          - live
          - sandbox

tags:
  - name: BIN info
    description: Lookup account and bank information for a given BIN of card number

paths:
  /bininfo/lists/{longId}:
    post:
      tags:
        - BIN info
      summary: Get BIN details
      description: Find account information details for a given BIN number
      operationId: getBinDetails
      parameters:
        - name: longId
          in: path
          description: |
            A `longId` of valid and active LIST session. Currently following statuses define
            active LIST session: `listed` and `functioning`
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BinDetailsRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BinDetailsResponse'
        "400":
          description: Request is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Session not found for given longId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Server-side error(s)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    BinDetailsRequest:
      type: object
      properties:
        binNumber:
          description: First 6 to 8 digits of a card PAN that identify issuing bank and account properties
          type: string
          example: "454617"
    BinDetailsResponse:
      type: object
      properties:
        brandName:
          type: string
          description: "Brand name of the payment account (for example: Mastercard Credit). If unavailable, `null` is displayed."
          example: DEBIT MASTERCARD
        bankName:
          type: string
          description: Name of the bank providing the payment account (the issuer). If unavailable, `null` or `UNKNOWN` is displayed.
          example: BANK_NAME
        networkCode:
          type: string
          description:
            Network code from the LIST response generated by the Server Payment API.

            Note that the codes of the networks that are not supported by Payoneer are also displayed. If unavailable, `null` is shown.
          example: MASTERCARD
        type:
          type: string
          description: "Type of card of the payment account (for example: Debit, Credit). If unavailable, `null` is displayed."
          example: DEBIT
    ErrorResponse:
      required:
        - message
      type: object
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
