swagger: '2.0'
info:
  version: 1.0.0
  title: Payments API
  description: OFX International payments and money transfer API.
host: sandbox.api.ofx.com
basePath: /v1
tags:
  - name: Quotes
  - name: Beneficiaries
  - name: Deals
  - name: Bank Accounts
  - name: Virtual Accounts
schemes:
  - https
securityDefinitions:
  oauth2:
    type: oauth2
    flow: application
    scopes:
      payments: Manage Payments in your account
    tokenUrl: 'https://sandbox.api.ofx.com/v1/oauth/token'
paths:
  /payments/beneficiaries:
    post:
      operationId: create beneficiary
      summary: Create a beneficiary
      tags:
        - Beneficiaries
      description: A beneficiary is the term given to the recipient of a payment made by OFX. All Beneficiaries are stored securely in our DB.
      security:
        - oauth2:
            - payments
    get:
      operationId: get beneficiaries
      summary: Gets a list of beneficiaries
      tags:
        - Beneficiaries
      description: Returns either an array of all your beneficiaries or a paged array of your beneficiaries
      security:
        - oauth2:
            - payments
  /payments/beneficiaries/validate:
    post:
      operationId: validate beneficiary
      summary: Validate a beneficiary
      tags:
        - Beneficiaries
      description: Validates the details of the beneficiary are correct.
      security:
        - oauth2:
            - payments
  '/payments/beneficiaries/{id}':
    get:
      operationId: Get User Beneficiary
      summary: Get User Beneficiary
      tags:
        - Beneficiaries
      description: Returns details of the User Beneficiary with ID.
      security:
        - oauth2:
            - payments
    delete:
      operationId: Delete beneficiary
      summary: Delete beneficiary
      tags:
        - Beneficiaries
      description: Will delete the User Beneficiary with the passed ID
      security:
        - oauth2:
            - payments
    put:
      operationId: Edit beneficiary
      summary: Update beneficiary
      tags:
        - Beneficiaries
      description: Updates the User Beneficiary details that has the passed ID.
      security:
        - oauth2:
            - payments
  /payments/deals:
    get:
      operationId: Gets a list of deals filtered by dealStatus and dealType and pagination.
      summary: Get a list of deals
      tags:
        - Deals
      description: Gets a list of deals per username filtered by dealStatus and dealType and pagination.
      security:
        - oauth2:
            - payments
    post:
      summary: Create a deal
      description: 'A Deal is a contract for buying or selling currency on the spot date (settlement date) which is normally 2 business days after the deal is booked (trade date).  When creating a Deal the following information needs to be included, Quote Id, Deal Information and Beneficiary. In addition, Ordering Customer information has to be sent in the create deal request when using the [client credential flow](/docs/payments-api/ZG9jOjM3NTQ3MzQ0-introduction#client-credentials-flow) to help[...]'
      operationId: Create a deal
      tags:
        - Deals
      security:
        - oauth2:
            - payments
  '/payments/deals/process/{id}':
    get:
      operationId: Gets the Id of the Deal from the process with the given ID
      summary: Get process result
      tags:
        - Deals
      description: 'Given a process ID, this service will return the id of the related deal.'
      security:
        - oauth2:
            - payments
      deprecated: true
  '/payments/deals/{id}/beneficiaries':
    get:
      operationId: Get deal beneficiaries
      summary: Get the list of beneficiaries for the given Deal Id
      tags:
        - Deals
      description: The request has succeeded. Response body will contain an array of the beneficiaries associated with the deal.
      security:
        - oauth2:
            - payments
  '/payments/deals/{id}/beneficiaries/{dealBeneficiaryId}':
    get:
      operationId: Get deal beneficiary
      summary: Get deal beneficiary
      tags:
        - Deals
      description: The request has succeeded. Response body will contain an array of the beneficiaries associated with the deal.
      security:
        - oauth2:
            - payments
  /payments/deals/spot:
    post:
      operationId: create spot deal
      summary: Create a spot deal
      tags:
        - Deals
      description: 'A Spot Deal is a contract for buying or selling currency on the spot date (settlement date) which is normally 2 business days after the deal is booked (trade date).  When creating a Spot Deal the following information needs to be included, Quote Id, Deal Information, Beneficiary, Ordering Customer.  Deals are processed and managed as as a long running process, when the deal has been created the ID of the process it is being managed on will be returned.  This processid can the[...]'
      security:
        - oauth2:
            - payments
      deprecated: true
  '/payments/deals/{id}':
    get:
      operationId: Get deal
      summary: Get a deal
      tags:
        - Deals
      description: 'Given the deal ID, this service will retrieve extra details of the deal. (please see /deals/process/{id} for details on how to retrieve a deal Id if you do not have it).'
      security:
        - oauth2:
            - payments
  '/payments/quotes/{id}/stale':
    get:
      operationId: get stale quote
      summary: Returns a state of quote
      tags:
        - Quotes
      description: This service will pick up any instances where the rate retrieved for the Quote has exceeded its timeout boundary and as such is considered stale. Deals cannot be created from stale rates used as quotes.
      security:
        - oauth2:
            - payments
  '/payments/quotes/{id}':
    get:
      operationId: get quote
      summary: Get a quote
      tags:
        - Quotes
      description: 'Given a Quote ID, will retrieve details of the quote.'
      security:
        - oauth2:
            - payments
    put:
      operationId: update quote
      summary: Update quote
      tags:
        - Quotes
      description: 'Updates an existing quote with number of beneficiaries. It helps to provide more accurate fee amount. '
      security:
        - oauth2:
            - payments
  /payments/quotes:
    post:
      operationId: create quote
      summary: Create a quote
      tags:
        - Quotes
      description: Creates a quote based on parameters that have been input.
      security:
        - oauth2:
            - payments
  '/bank-accounts/template/{country}/{currency}/{accountType}':
    get:
      operationId: get bank accounts template
      summary: Get bank accounts template
      tags:
        - Bank Accounts
      description: 'Get bank accounts template for given country, currency and accountType'
      security:
        - oauth2:
            - payments
  '/bank-accounts/details/{country}/{currency}/{routingType}/{routingCode}':
    get:
      operationId: get bank accounts details
      summary: Get bank accounts details
      tags:
        - Bank Accounts
      description: 'Get bank accounts details for given country, currency, routingType and routingCode. <p> NOTE: Some responses may not contain values for all fields. If the returned values are to be used elsewhere, e.g. to create a Beneficiary, then the details should be validated prior to use, and a method for manual entry of mandatory details provided if required.</p>'
      security:
        - oauth2:
            - payments
  /virtualaccounts:
    get:
      operationId: get a list of virtual accounts
      summary: Get a list of virtual accounts
      tags:
        - Virtual Accounts
      description: 'Get a list of virtual accounts for a user. This endpoint may only be used by customers outside the EU and UK. For EU and UK customers where PSD2 regulations apply, refer to [AISP API](https://api-docs.ofx.com/docs/aisp-api/ZG9jOjQ1Mg-gca-aisp-api) endpoints.'
      security:
        - oauth2:
            - payments
  '/virtualaccounts/{virtualAccountId}':
    get:
      operationId: get a virtual account
      summary: Get a virtual account
      tags:
        - Virtual Accounts
      description: 'Given the virtual account ID, this endpoint will retrieve virtual account details. This endpoint may only be used by customers outside the EU and UK. For EU and UK customers where PSD2 regulations apply, refer to [AISP API](https://api-docs.ofx.com/docs/aisp-api/ZG9jOjQ1Mg-gca-aisp-api) endpoints.'
      security:
        - oauth2:
            - payments
  '/virtualaccounts/{virtualAccountId}/balance':
    get:
      operationId: get a virtual account balance
      summary: Get a virtual account balance
      tags:
        - Virtual Accounts
      description: 'Given the virtual account ID, this endpoint will retrieve virtual account balance details. This endpoint may only be used by customers outside the EU and UK. For EU and UK customers where PSD2 regulations apply, refer to [AISP API](https://api-docs.ofx.com/docs/aisp-api/ZG9jOjQ1Mg-gca-aisp-api) endpoints.'
      security:
        - oauth2:
            - payments
  '/virtualaccounts/{virtualAccountId}/transactions':
    get:
      operationId: get a list of virtual account transactions
      summary: Get a list of virtual account transactions
      tags:
        - Virtual Accounts
      description: 'Given the virtual account ID, this endpoint will retrieve a list of virtual account transactions. This endpoint may only be used by customers outside the EU and UK. For EU and UK customers where PSD2 regulations apply, refer to [AISP API](https://api-docs.ofx.com/docs/aisp-api/ZG9jOjQ1Mg-gca-aisp-api) endpoints.'
      security:
        - oauth2:
            - payments
  /virtualaccounts/transfers:
    post:
      operationId: Initiate an interwallet transfer
      summary: Initiate interwallet transfer
      tags:
        - Virtual Accounts
      description: Initiate an interwallet transfer between virtual accounts based on parameters that have been input.
      security:
        - oauth2:
            - payments
  '/virtualaccounts/transfers/{transferId}':
    get:
      operationId: get an interwallet transfer state
      summary: Get interwallet transfer state
      tags:
        - Virtual Accounts
      description: 'Given a transfer Id, this endpoint will return the state of this transfer.'
      security:
        - oauth2:
            - payments
  '/payment-reasons/{sellCurrency}':
    get:
      operationId: Get Payment Reasons
      summary: Get Payment Reasons
      tags:
        - Reference
      description: Get payment reasons for a provided sell currency
      security:
        - oauth2:
            - payments
  /reference/countries:
    get:
      operationId: Get Countries
      summary: Get Countries
      tags:
        - Reference
      description: Get valid list of countries supported by OFX.
      security:
        - oauth2:
            - reference
  /reference/traded-currencies:
    get:
      operationId: Get Currencies
      summary: Get Currencies
      tags:
        - Reference
      description: Get list of supported currencies against the country.
      security:
        - oauth2:
            - reference