openapi: 3.0.1
info:
  title: na.internal.enterprise.quotedemo
  description: This is quoue API for Demo purpose
  version: '1.0'
servers:
  - url: https://nauat08.chubbdigital.com/enterprise.quotedemo
  - url: https://nauat.chubbdigital.com/enterprise.quotedemo
  - url: https://dp-uat.digitalgateway.chubb.com/enterprise.quotedemo
  - url: https://mtls-uat.na.digitalgateway.chubb.com/enterprise.quotedemo
  - url: https://na-central-uat.chubbdigital.com/enterprise.quotedemo
paths:
  /registerquote:
    get:
      summary: registerquote
      description: Register a quote
      operationId: registerquote
      responses:
        '200':
          description: 'null'
components: { }