export type SDKLanguage = "C#" | "PHP" | "Python" | "Go" | "JavaScript" | "Java" | "Ruby" | "TypeScript"
export type Category = "Fintech" | "E-commerce" | "Payments" | "Crypto" | "Banking" | "Identity"
export type Status = "NEWEST ADDITION" | "HAND CURATED" | "FEATURED" | "POPULAR" | "STAFF PICK" | null

export interface Portal {
  name: string
  url: string
  logoUrl: string
  description: string
  category: Category
  status?: Status
  sdks: SDKLanguage[]
  addedAt: string // ISO date string
  screenshotUrl?: string // New field for screenshots
}

export const portals: Portal[] = [
  {
    name: "akahu",
    url: "https://apimatic-akahu.web.app",
    logoUrl: "https://img.logo.dev/www.akahu.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for akahu",
    category: "Fintech",
    status: "STAFF PICK",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/e4f2fd/1a73e8?text=Akahu+API+Portal",
  },
  {
    name: "hipay",
    url: "http://hipay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.hipay.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for hipay",
    category: "Fintech",
    status: "HAND CURATED",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/e4f2fd/1a73e8?text=Hipay+API+Portal",
  },
  {
    name: "worldline",
    url: "http://worldline-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.worldline.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for worldline",
    category: "Fintech",
    status: "STAFF PICK",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/e4f2fd/1a73e8?text=Worldline+API+Portal",
  },
  {
    name: "ramp",
    url: "http://ramp-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ramp.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ramp",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Ramp+API+Portal",
  },
  {
    name: "sumup",
    url: "http://sumup-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.sumup.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for sumup",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=SumUp+API+Portal",
  },
  {
    name: "revolut",
    url: "http://revolut-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.revolut.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for revolut",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Revolut+API+Portal",
  },
  {
    name: "payrix",
    url: "http://payrix-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payrix.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for payrix",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Payrix+API+Portal",
  },
  {
    name: "payroc",
    url: "http://payroc-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payroc.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for payroc",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Payroc+API+Portal",
  },
  {
    name: "nium",
    url: "http://nium-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.nium.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for nium",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Nium+API+Portal",
  },
  {
    name: "pxp-solutions",
    url: "http://pxp-solutions-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.pxp-solutions.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for pxp-solutions",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=PXP+Solutions+API+Portal",
  },
  {
    name: "ppro",
    url: "http://ppro-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ppro.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ppro",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=PPRO+API+Portal",
  },
  {
    name: "paylocity",
    url: "http://paylocity-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paylocity.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paylocity",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Paylocity+API+Portal",
  },
  {
    name: "payoneer",
    url: "http://payoneer-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payoneer.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for payoneer",
    category: "Fintech",
    status: "FEATURED",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/e4f2fd/1a73e8?text=Payoneer+API+Portal",
  },
  {
    name: "moneyhub",
    url: "http://moneyhub-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.moneyhub.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for moneyhub",
    category: "Fintech",
    status: "POPULAR",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/e4f2fd/1a73e8?text=MoneyHub+API+Portal",
  },
  {
    name: "n26",
    url: "http://n26-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.n26.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for n26",
    category: "Fintech",
    status: "NEWEST ADDITION",
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/e4f2fd/1a73e8?text=N26+API+Portal",
  },
  {
    name: "modular",
    url: "http://modular-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.modulrfinance.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for modular",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Modular+API+Portal",
  },
  {
    name: "merchante",
    url: "http://merchante-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.merchante.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for merchante",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Merchante+API+Portal",
  },
  {
    name: "mastercard",
    url: "http://mastercard-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mastercard.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mastercard",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Mastercard+API+Portal",
  },
  {
    name: "jp-morgan-chase",
    url: "http://jp-morgan-chase-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.jpmorganchase.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for jp-morgan-chase",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=JP+Morgan+Chase+API+Portal",
  },
  {
    name: "klarna-apis",
    url: "http://klarna-apis-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.klarna.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for klarna-apis",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Klarna+APIs+API+Portal",
  },
  {
    name: "coinbase",
    url: "http://coinbase-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.coinbase.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for coinbase",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Coinbase+API+Portal",
  },
  {
    name: "fiserv",
    url: "http://fiserv-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.fiserv.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for fiserv",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Fiserv+API+Portal",
  },
  {
    name: "conekta",
    url: "http://conekta-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.conekta.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for conekta",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Conekta+API+Portal",
  },
  {
    name: "dwolla",
    url: "http://dwolla-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.dwolla.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for dwolla",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Dwolla+API+Portal",
  },
  {
    name: "galileo-ft",
    url: "http://galileo-ft-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.galileo-ft.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for galileo-ft",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Galileo+FT+API+Portal",
  },
  {
    name: "elavon",
    url: "http://elavon-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.elavon.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for elavon",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Elavon+API+Portal",
  },
  {
    name: "cybersource",
    url: "http://cybersource-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.cybersource.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for cybersource",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=CyberSource+API+Portal",
  },
  {
    name: "celcoin",
    url: "http://celcoin-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.celcoin.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for celcoin",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Celcoin+API+Portal",
  },
  {
    name: "clip",
    url: "http://clip-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payclip.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for clip",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Clip+API+Portal",
  },
  {
    name: "adyen",
    url: "http://adyen-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payadyen.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for adyen",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Adyen+API+Portal",
  },
  {
    name: "bolt",
    url: "http://bolt-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paybolt.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bolt",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Bolt+API+Portal",
  },
  {
    name: "brex",
    url: "http://brex-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paybrex.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for brex",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Brex+API+Portal",
  },
  {
    name: "marqeta",
    url: "http://marqeta-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.marqeta.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for marqeta",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Marqeta+API+Portal",
  },
  {
    name: "form3",
    url: "http://form3-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.form3.tech?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for form3",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Form3+API+Portal",
  },
  {
    name: "ccbill",
    url: "http://ccbill-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ccbill.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ccbill",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=CCBill+API+Portal",
  },
  {
    name: "izettle",
    url: "http://izettle-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.izettle.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for izettle",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=iZettle+API+Portal",
  },
  {
    name: "paysafe",
    url: "http://paysafe-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paysafe.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paysafe",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Paysafe+API+Portal",
  },
  {
    name: "banksapi",
    url: "http://banksapi-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.banksapi.de?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for banksapi",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=BanksAPI+API+Portal",
  },
  {
    name: "basiq",
    url: "http://basiq-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.basiq.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for basiq",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Basiq+API+Portal",
  },
  {
    name: "ayoconnect",
    url: "http://ayoconnect-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ayoconnect.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ayoconnect",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Ayoconnect+API+Portal",
  },
  {
    name: "banqware",
    url: "http://banqware-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.banqware.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for banqware",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Banqware+API+Portal",
  },
  {
    name: "akurateco",
    url: "http://akurateco-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.akurateco.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for akurateco",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Akurateco+API+Portal",
  },
  {
    name: "arcopay",
    url: "http://arcopay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.arcopay.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for arcopay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Arcopay+API+Portal",
  },
  {
    name: "afterbanks",
    url: "http://afterbanks-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.afterbanks.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for afterbanks",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Afterbanks+API+Portal",
  },
  {
    name: "rapyd",
    url: "http://rapyd-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.rapyd.net?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for rapyd",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Rapyd+API+Portal",
  },
  {
    name: "yapily",
    url: "http://yapily-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.yapily.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for yapily",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Yapily+API+Portal",
  },
  {
    name: "wyre",
    url: "http://wyre-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.sendwyre.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for wyre",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Wyre+API+Portal",
  },
  {
    name: "tyro-payments",
    url: "http://tyro-payments-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.tyro.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for tyro-payments",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Tyro+Payments+API+Portal",
  },
  {
    name: "xsolla",
    url: "http://xsolla-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.xsolla.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for xsolla",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Xsolla+API+Portal",
  },
  {
    name: "schufa-holding",
    url: "http://schufa-holding-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.schufa.de?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for schufa-holding",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Schufa+Holding+API+Portal",
  },
  {
    name: "verifone",
    url: "http://verifone-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.verifone.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for verifone",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Verifone+API+Portal",
  },
  {
    name: "siliconvalleybank",
    url: "http://siliconvalleybank-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.svb.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for siliconvalleybank",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Silicon+Valley+Bank+API+Portal",
  },
  {
    name: "ebanx",
    url: "http://ebanx-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ebanx.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ebanx",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Ebanx+API+Portal",
  },
  {
    name: "zolando",
    url: "http://zolando-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.zolando.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for zolando",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Zolando+API+Portal",
  },
  {
    name: "mollie",
    url: "http://mollie-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mollie.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mollie",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Mollie+API+Portal",
  },
  {
    name: "zip-co",
    url: "http://zip-co-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.zip.co?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for zip-co",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Zip+Co+API+Portal",
  },
  {
    name: "zai",
    url: "http://zai-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.hellozai.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for zai",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Zai+API+Portal",
  },
  {
    name: "tink",
    url: "http://tink-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.tink.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for tink",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Tink+API+Portal",
  },
  {
    name: "mone",
    url: "http://mone-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mone.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mone",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Mone+API+Portal",
  },
  {
    name: "lukka",
    url: "http://lukka-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.lukka.tech?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for lukka",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Lukka+API+Portal",
  },
  {
    name: "moonpay",
    url: "http://moonpay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.moonpay.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for moonpay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Moonpay+API+Portal",
  },
  {
    name: "gusto",
    url: "http://gusto-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.gusto.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for gusto",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Gusto+API+Portal",
  },
  {
    name: "injective",
    url: "http://injective-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.injective.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for injective",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Injective+API+Portal",
  },
  {
    name: "mercury",
    url: "http://mercury-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mercury.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mercury",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Mercury+API+Portal",
  },
  {
    name: "homelight",
    url: "http://homelight-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.homelight.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for homelight",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Homelight+API+Portal",
  },
  {
    name: "mambu",
    url: "http://mambu-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mambu.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mambu",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Mambu+API+Portal",
  },
  {
    name: "lunar",
    url: "http://lunar-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.lunar.app?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for lunar",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Lunar+API+Portal",
  },
  {
    name: "ledger",
    url: "http://ledger-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.ledger.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for ledger",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Ledger+API+Portal",
  },
  {
    name: "kraken",
    url: "http://kraken-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.kraken.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for kraken",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Kraken+API+Portal",
  },
  {
    name: "uniswap",
    url: "http://uniswap-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.uniswap.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for uniswap",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Uniswap+API+Portal",
  },
  {
    name: "trulioo",
    url: "http://trulioo-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.trulioo.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for trulioo",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Trulioo+API+Portal",
  },
  {
    name: "avant",
    url: "http://avant-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.avant.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for avant",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Avant+API+Portal",
  },
  {
    name: "circle",
    url: "http://circle-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.circle.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for circle",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Circle+API+Portal",
  },
  {
    name: "addepar",
    url: "http://addepar-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.addepar.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for addepar",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Addepar+API+Portal",
  },
  {
    name: "carta",
    url: "http://carta-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.carta.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for carta",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Carta+API+Portal",
  },
  {
    name: "coinlist",
    url: "http://coinlist-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.coinlist.co?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for coinlist",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Coinlist+API+Portal",
  },
  {
    name: "chippercash",
    url: "http://chippercash-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.chippercash.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for chippercash",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Chippercash+API+Portal",
  },
  {
    name: "clearstreet",
    url: "http://clearstreet-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.clearstreet.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for clearstreet",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Clearstreet+API+Portal",
  },
  {
    name: "blockchain",
    url: "http://blockchain-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.blockchain.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for blockchain",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Blockchain+API+Portal",
  },
  {
    name: "openpayd",
    url: "http://openpayd-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.openpayd.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for openpayd",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Openpayd+API+Portal",
  },
  {
    name: "crosskey",
    url: "http://crosskey-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.crosskey.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for crosskey",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Crosskey+API+Portal",
  },
  {
    name: "dapi",
    url: "http://dapi-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.dapi.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for dapi",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Dapi+API+Portal",
  },
  {
    name: "mondu",
    url: "http://mondu-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mondu.ai?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mondu",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Mondu+API+Portal",
  },
  {
    name: "paynova",
    url: "http://paynova-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paynova.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paynova",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Paynova+API+Portal",
  },
  {
    name: "crezco",
    url: "http://crezco-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.crezco.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for crezco",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Crezco+API+Portal",
  },
  {
    name: "codat",
    url: "http://codat-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.codat.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for codat",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Codat+API+Portal",
  },
  {
    name: "belvo",
    url: "http://belvo-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.belvo.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for belvo",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Belvo+API+Portal",
  },
  {
    name: "akoya",
    url: "http://akoya-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.akoya.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for akoya",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Akoya+API+Portal",
  },
  {
    name: "mx",
    url: "http://mx-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.mx.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for mx",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=MX+API+Portal",
  },
  {
    name: "figo",
    url: "http://figo-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.figopayment.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for figo",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Figo+API+Portal",
  },
  {
    name: "bud",
    url: "http://bud-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.thisisbud.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bud",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Bud+API+Portal",
  },
  {
    name: "bunq",
    url: "http://bunq-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.bunq.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bunq",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Bunq+API+Portal",
  },
  {
    name: "fireblocks",
    url: "http://fireblocks-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.fireblocks.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for fireblocks",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Fireblocks+API+Portal",
  },
  {
    name: "floqast",
    url: "http://floqast-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.floqast.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for floqast",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Floqast+API+Portal",
  },
  {
    name: "flutterwave",
    url: "http://flutterwave-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.flutterwave.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for flutterwave",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Flutterwave+API+Portal",
  },
  {
    name: "figment",
    url: "http://figment-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.figment.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for figment",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Figment+API+Portal",
  },
  {
    name: "flow",
    url: "http://flow-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.flow.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for flow",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Flow+API+Portal",
  },
  {
    name: "truelayer",
    url: "http://truelayer-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.truelayer.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for truelayer",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Truelayer+API+Portal",
  },
  {
    name: "the-bank-of-london",
    url: "http://the-bank-of-london-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.thebankoflondon.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for the-bank-of-london",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=The+Bank+of+London+API+Portal",
  },
  {
    name: "teya",
    url: "http://teya-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.teya.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for teya",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Teya+API+Portal",
  },
  {
    name: "paxos",
    url: "http://paxos-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paxos.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paxos",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Paxos+API+Portal",
  },
  {
    name: "symphony",
    url: "http://symphony-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.symphony.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for symphony",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Symphony+API+Portal",
  },
  {
    name: "snapdocs",
    url: "http://snapdocs-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.snapdocs.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for snapdocs",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Snapdocs+API+Portal",
  },
  {
    name: "neon",
    url: "http://neon-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.neon.tech?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for neon",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Neon+API+Portal",
  },
  {
    name: "paystand",
    url: "http://paystand-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paystand.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paystand",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Paystand+API+Portal",
  },
  {
    name: "taxbit",
    url: "http://taxbit-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.taxbit.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for taxbit",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Taxbit+API+Portal",
  },
  {
    name: "solaris",
    url: "http://solaris-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.solaris.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for solaris",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Solaris+API+Portal",
  },
  {
    name: "kudosity",
    url: "http://kudosity-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.kudosity.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for kudosity",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Kudosity+API+Portal",
  },
  {
    name: "inxpress",
    url: "http://inxpress-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.inxpress.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for inxpress",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Inxpress+API+Portal",
  },
  {
    name: "clickatell",
    url: "http://clickatell-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.clickatell.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for clickatell",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Clickatell+API+Portal",
  },
  {
    name: "fastspring",
    url: "http://fastspring-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.fastspring.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for fastspring",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Fastspring+API+Portal",
  },
  {
    name: "global-freight-solutions",
    url: "http://global-freight-solutions-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.gfsdeliver.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for global-freight-solutions",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Global+Freight+Solutions+API+Portal",
  },
  {
    name: "bandwidth",
    url: "http://bandwidth-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.bandwidth.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bandwidth",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Bandwidth+API+Portal",
  },
  {
    name: "heymarket",
    url: "http://heymarket-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.heymarket.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for heymarket",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Heymarket+API+Portal",
  },
  {
    name: "bambora",
    url: "http://bambora-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.bambora.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bambora",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Bambora+API+Portal",
  },
  {
    name: "truelayer",
    url: "http://truelayer-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.truelayer.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for truelayer",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Truelayer+API+Portal",
  },
  {
    name: "dojo",
    url: "http://dojo-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.dojo.tech?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for dojo",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Dojo+API+Portal",
  },
  {
    name: "keybank",
    url: "http://keybank-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.keybank.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for keybank",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Keybank+API+Portal",
  },
  {
    name: "luminor",
    url: "http://luminor-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.luminor.lt?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for luminor",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Luminor+API+Portal",
  },
  {
    name: "finix",
    url: "http://finix-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.finix.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for finix",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Finix+API+Portal",
  },
  {
    name: "fnz-group",
    url: "http://fnz-group-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.fnz-group.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for fnz-group",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=FNZ+Group+API+Portal",
  },
  {
    name: "jumio",
    url: "http://jumio-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.jumio.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for jumio",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Jumio+API+Portal",
  },
  {
    name: "great-american-insurance",
    url: "http://great-american-insurance-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.greatamericaninsurancegroup.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for great-american-insurance",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Great+American+Insurance+API+Portal",
  },
  {
    name: "corpay",
    url: "http://corpay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.corpay.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for corpay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Corpay+API+Portal",
  },
  {
    name: "deutsche-bank",
    url: "http://deutsche-bank-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.deutsche-bank.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for deutsche-bank",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Deutsche+Bank+API+Portal",
  },
  {
    name: "common-wealth-bank",
    url: "http://common-wealth-bank-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.commbank.com.au?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for common-wealth-bank",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Common+Wealth+Bank+API+Portal",
  },
  {
    name: "check",
    url: "http://check-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.checkhq.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for check",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Check+API+Portal",
  },
  {
    name: "dnb",
    url: "http://dnb-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.dnb.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for dnb",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=DNB+API+Portal",
  },
  {
    name: "bakkt",
    url: "http://bakkt-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.bakkt.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bakkt",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Bakkt+API+Portal",
  },
  {
    name: "experian",
    url: "http://experian-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.experian.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for experian",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Experian+API+Portal",
  },
  {
    name: "chubb",
    url: "http://chubb-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.chubb.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for chubb",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Chubb+API+Portal",
  },
  {
    name: "bnp-paribas",
    url: "http://bnp-paribas-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.group.bnpparibas?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for bnp-paribas",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=BNP+Paribas+API+Portal",
  },
  {
    name: "dock-tech",
    url: "http://dock-tech-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.dock-tech.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for dock-tech",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Dock+Tech+API+Portal",
  },
  {
    name: "cigna",
    url: "http://cigna-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.cigna.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for cigna",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Cigna+API+Portal",
  },
  {
    name: "nab",
    url: "http://nab-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.nab.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for nab",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=NAB+API+Portal",
  },
  {
    name: "north-american-bancard",
    url: "http://north-american-bancard-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.north.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for north-american-bancard",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=North+American+Bancard+API+Portal",
  },
  {
    name: "railsr",
    url: "http://railsr-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.railsr.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for railsr",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Railsr+API+Portal",
  },
  {
    name: "satispay",
    url: "http://satispay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.satispay.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for satispay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Satispay+API+Portal",
  },
  {
    name: "payfit",
    url: "http://payfit-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.payfit.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for payfit",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Payfit+API+Portal",
  },
  {
    name: "sovos",
    url: "http://sovos-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.sovos.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for sovos",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Sovos+API+Portal",
  },
  {
    name: "rootplatform",
    url: "http://rootplatform-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.rootplatform.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for rootplatform",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Rootplatform+API+Portal",
  },
  {
    name: "scalapay",
    url: "http://scalapay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.scalapay.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for scalapay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Scalapay+API+Portal",
  },
  {
    name: "orum",
    url: "http://orum-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.orum.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for orum",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Orum+API+Portal",
  },
  {
    name: "santander-uk",
    url: "http://santander-uk-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.santander.co.uk?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for santander-uk",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Santander+UK+API+Portal",
  },
  {
    name: "opensea",
    url: "http://opensea-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.opensea.io?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for opensea",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Opensea+API+Portal",
  },
  {
    name: "sagesure",
    url: "http://sagesure-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.sagesure.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for sagesure",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Sagesure+API+Portal",
  },
  {
    name: "solid",
    url: "http://solid-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.solidifi.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for solid",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Solid+API+Portal",
  },
  {
    name: "paymob",
    url: "http://paymob-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.paymob.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for paymob",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Paymob+API+Portal",
  },
  {
    name: "sila",
    url: "http://sila-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.silamoney.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for sila",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Sila+API+Portal",
  },
  {
    name: "treasure-data",
    url: "http://treasure-data-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.treasuredata.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for treasure-data",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Treasure+Data+API+Portal",
  },
  {
    name: "token",
    url: "http://token-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.token.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for token",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Token+API+Portal",
  },
  {
    name: "toast",
    url: "http://toast-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.pos.toasttab.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for toast",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Toast+API+Portal",
  },
  {
    name: "veem",
    url: "http://veem-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.veem.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for veem",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Veem+API+Portal",
  },
  {
    name: "vipps-mobilepay",
    url: "http://vipps-mobilepay-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.vipps.no?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for vipps-mobilepay",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Vipps+MobilePay+API+Portal",
  },
  {
    name: "sumsub",
    url: "http://sumsub-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.sumsub.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for sumsub",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Sumsub+API+Portal",
  },
  {
    name: "western-union",
    url: "http://western-union-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.westernunion.com/?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for western-union",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Western+Union+API+Portal",
  },
  {
    name: "zeta-tech",
    url: "http://zeta-tech-apimatic-catalog.pages.dev",
    logoUrl: "https://img.logo.dev/www.zeta-tech.com?token=pk_C1elIw7HR2yyKFwdqgPYHA",
    description: "API portal for zeta-tech",
    category: "Fintech",
    status: null,
    sdks: ["Python", "TypeScript", "C#", "PHP", "Go", "Java", "Ruby"],
    addedAt: "2025-03-12",
    screenshotUrl: "https://placehold.co/600x400/f0f0f0/555555?text=Zeta+Tech+API+Portal",
  },
]

