openapi: 3.0.1
info:
  title: na.internal.enterprise.Policydemo
  description: This is policy API for Demo purpose
  version: '1.0'
servers:
  - url: https://nauat08.chubbdigital.com/enterprise.Policydemo
  - url: https://nauat.chubbdigital.com/enterprise.Policydemo
  - url: https://dp-uat.digitalgateway.chubb.com/enterprise.Policydemo
  - url: https://mtls-uat.na.digitalgateway.chubb.com/enterprise.Policydemo
  - url: https://na-central-uat.chubbdigital.com/enterprise.Policydemo
paths:
  /registerpolicy:
    get:
      summary: RegisterPolicy
      description: Register a policy
      operationId: RegisterPolicy
      responses:
        '200':
          description: 'null'
components: { }