openapi: 3.0.1
info:
  title: na.internal.enterprise.authorization
  description: 'The Tokens resource allows you to generate an Authorization Token, based on App_ID and App_Key. This token must then be sent in the Authorization Header of all API calls.'
  version: '1'
servers:
  - url: https://latam-uat.digitalgateway.chubb.com/enterprise.operations.authorization
  - url: https://nauat08.chubbdigital.com/enterprise.operations.authorization
  - url: https://nauat.chubbdigital.com/enterprise.operations.authorization
  - url: https://dp-uat.digitalgateway.chubb.com/enterprise.operations.authorization
  - url: https://mtls-uat.na.digitalgateway.chubb.com/enterprise.operations.authorization
  - url: https://na-central-uat.chubbdigital.com/enterprise.operations.authorization
paths:
  /:
    post:
      tags:
        - token-test2
        - token-test1
      summary: Generate
      description: 'Generate and return an Authorization Token, to be used with all subsequent API calls.'
      operationId: getAccessToken
      parameters:
        - name: App_ID
          in: header
          description: App_ID supplied by CHUBB
          required: true
          schema:
            type: string
        - name: App_Key
          in: header
          description: App_Key supplied by CHUBB
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '400':
          description: App_ID/App_key Header is not found
        '500':
          description: Actual Exception message
  /TokenAvailability:
    get:
      summary: Availability
      description: Checks Token API Availability
      operationId: availability
      responses:
        '200':
          description: 'null'
components: { }