openapi: 3.0.1
info:
  title: na.external.digital.api.tokens-clone
  description: 'The Tokens resource allows you to generate an Authorization Token, based on App_ID and App_Key. This token must then be sent in the Authorization Header of all API calls.'
  version: ''
servers:
  - url: https://nauat08.chubbdigital.com/api/v1/tokens-clone
  - url: https://nauat.chubbdigital.com/api/v1/tokens-clone
  - url: https://dp-uat.digitalgateway.chubb.com/api/v1/tokens-clone
  - url: https://mtls-uat.na.digitalgateway.chubb.com/api/v1/tokens-clone
  - url: https://na-central-uat.chubbdigital.com/api/v1/tokens-clone
paths:
  /:
    post:
      summary: Generate
      description: 'Generate and return an Authorization Token, to be used with all subsequent API calls.'
      operationId: 5be35304b0064c9f04ff3c73
      parameters:
        - name: App_ID
          in: header
          description: App_ID supplied by CHUBB
          required: true
          schema:
            type: string
        - name: App_Key
          in: header
          description: App_Key supplied by CHUBB
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '400':
          description: App_ID/App_key Header is not found
        '500':
          description: Actual Exception message
components: { }