openapi: 3.0.1
info:
  title: Lunar Banking Services Connectivity API
  description: Connectivity API
  version: 1.0.0
servers:
  - url: 'https://api.banking-services.lunar.app'
  - url: 'https://api.banking-services-sandbox.lunar.app'
paths:
  /v1/connectivity/whoami:
    get:
      security:
        - oauth: [ ]
      description:
        Validate access credentials and get registered organization.
      responses:
        '200':
          description: Organization name as registered in Lunar.
          content:
            application/json:
              schema:
                type: object
                properties:
                  organizationName:
                    type: string
              example:
                {
                  "organizationName": "Trusted Services AS"
                }
        default:
          description: |
            Unexpected error occurred.
            
            HTTP status code will be in 500 range.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInternalErrorResponse'
components:
  securitySchemes:
    oauth:
      type: oauth2
      description: Oauth2 authentication for Banking Services APIs.
      flows:
        clientCredentials:
          tokenUrl: https://signin.authx.prod.lunar.app
          scopes: { }
  schemas:
    ErrorInternalErrorResponse:
      required:
        - message
        - type
      type: object
      description: Resource not found.
      properties:
        message:
          type: string
          description: Human readable error message.
        type:
          type: string
          enum:
            - INTERNAL_ERROR
