openapi: 3.0.0
info:
  title: HomeLight API
  description: API for managing real estate leads and related data.
  version: 1.0.0
servers:
  - url: https://staging.homelight.com/api
    description: Staging environment
  - url: https://www.homelight.com/api
    description: Production environment

paths:
  /partner_lead/v2:
    post:
      summary: Create a lead
      operationId: createLead
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                homelight-partner-lead-request:
                  type: object
                  properties:
                    secret:
                      type: string
                      description: Secret key for authentication
                    token:
                      type: string
                      description: Token for authentication
                    leads:
                      type: array
                      items:
                        type: object
                        properties:
                          city:
                            type: string
                            example: San Francisco, CA
                          email:
                            type: string
                            example: daniel@homelight.com
                          name:
                            type: string
                            example: Daniel Duke
                          phone:
                            type: string
                            example: 214.336.0515
                          price:
                            type: number
                            example: 123456
                          property-type:
                            type: string
                            enum:
                              - single_family_home
                              - condominium
                              - townhomes
                              - other
                          user-type:
                            type: string
                            enum:
                              - buyer
                              - seller
      responses:
        '200':
          description: Successful lead creation
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: object
                    properties:
                      leads_accepted:
                        type: integer
                        example: 1
                      leads_rejected:
                        type: integer
                        example: 0
                  leads:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: Daniel Duke
                        accepted:
                          type: boolean
                          example: true
        '400':
          description: Invalid request
        '401':
          description: Authentication failed

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []
