openapi: 3.0.1
info:
  title: na.internal.a-h.weekwork1.1
  description: 'A sample API with information related to a technical conference.  The available resources  include *Speakers*, *Sessions* and *Topics*.  A single write operation is available to provide  feedback on a session.'
  version: '1'
servers:
  - url: https://nauat08.chubbdigital.com/claims.weekwork1
  - url: https://nauat.chubbdigital.com/claims.weekwork1
  - url: https://dp-uat.digitalgateway.chubb.com/claims.weekwork1
  - url: https://mtls-uat.na.digitalgateway.chubb.com/claims.weekwork1
  - url: https://na-central-uat.chubbdigital.com/claims.weekwork1
paths:
  '/session/{id}':
    get:
      summary: GetSession
      description: Retreive a representation of a single session by Id
      operationId: GetSession
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
        - name: Authorization
          in: header
          description: ADB2C JWT Bearer token for OAuth authentication
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json: { }
        '500':
          description: Internal Server Error
          content:
            application/json: { }
    post:
      summary: SubmitSession
      description: Retreive a representation of a single session by Id
      operationId: SubmitSession
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
        - name: Authorization
          in: header
          description: ADB2C JWT Bearer token for OAuth authentication
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body'
            example: string
      responses:
        '200':
          description: OK
          content:
            application/json: { }
        '500':
          description: Internal Server Error
          content:
            application/json: { }
    delete:
      summary: DeleteSession
      description: Retreive a representation of a single session by Id
      operationId: DeleteSession
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
        - name: Authorization
          in: header
          description: ADB2C JWT Bearer token for OAuth authentication
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json: { }
        '500':
          description: Internal Server Error
          content:
            application/json: { }
  '/session/{id}/topics':
    get:
      summary: GetSessionTopics
      description: A list of topics covered by a particular session
      operationId: GetSessionTopics
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
        - name: Authorization
          in: header
          description: ADB2C JWT Bearer token for OAuth authentication
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json: { }
        '500':
          description: Internal Server Error
          content:
            application/json: { }
  '/session/{id}/feedback':
    put:
      summary: UpdateSession
      description: Update a representation of a single session by Id
      operationId: UpdateSession
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
        - name: Authorization
          in: header
          description: ADB2C JWT Bearer token for OAuth authentication
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body'
            example: string
      responses:
        '200':
          description: OK
          content:
            application/json: { }
        '500':
          description: Internal Server Error
          content:
            application/json: { }
  /sessions:
    get:
      tags:
        - Approval
      summary: GetSessions
      description: A list of sessions.  Optional parameters work as filters to reduce the listed sessions.
      operationId: GetSessions
      parameters:
        - name: speakername
          in: query
          schema:
            type: string
        - name: dayno
          in: query
          description: Format - int32.
          schema:
            type: integer
        - name: keyword
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          description: ADB2C JWT Bearer token for OAuth authentication
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/vnd.collection+json: { }
        '500':
          description: Internal Server Error
          content:
            application/vnd.collection+json: { }
components:
  schemas:
    Body:
      type: string
      example: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]