{
  "openapi": "3.0.0",
  "info": {
    "title": "MyParcel.com API Specification",
    "description": "**Introduction**<br>This is the technical reference for the MyParcel.com API implementing the [OpenApi 3.0 Specification](https://github.com/OAI/OpenAPI-Specification) according to [JSON API](https://jsonapi.org) conventions.<br>Check our [API documentation](https://docs.myparcel.com) for more information and code examples.<br>Check our [GitHub releases](https://github.com/MyParcelCOM/api-specification/releases) for a complete version history.<br><br>⚠ Some endpoints are mark[...]",
    "termsOfService": "https://www.myparcel.com/legal",
    "contact": {
      "name": "Tech Support",
      "url": "https://www.myparcel.com/contact",
      "email": "support@myparcel.com"
    },
    "license": {
      "name": "pricing",
      "url": "https://www.myparcel.com/pricing"
    },
    "version": "v1.73.1",
    "x-logo": {
      "url": "https://cdn.myparcel.com/images/myparcelcom-black.svg"
    }
  },
  "servers": [
    {
      "url": "https://api.myparcel.com"
    }
  ],
  "paths": {
    "/add-shipments-to-collection": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "collections.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Add shipments to collection.",
        "description": "This endpoint can add multiple shipments to a concept collection."
      }
    },
    "/addresses": {
      "get": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get all addresses for a user.",
        "description": "This endpoint retrieves all address entries that the requesting user has access to."
      },
      "post": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Create a new address entry.",
        "description": "This endpoint creates a new address from the posted data."
      }
    },
    "/addresses/{address_id}": {
      "get": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get an address by ID.",
        "description": "This endpoint retrieves the address with the supplied ID."
      },
      "patch": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Update an address by ID.",
        "description": "This endpoint updates the address with the supplied ID."
      },
      "delete": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Delete an address by ID.",
        "description": "This endpoint deletes the address with the supplied ID."
      }
    },
    "/brokers": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          },
          {
            "OAuth2": [
              "enterprises.manage"
            ]
          }
        ],
        "summary": "Get all available brokers.",
        "description": "This endpoint retrieves brokers available to your API client. If your client is created within our `MyParcel.com` portal, it will be connected to 1 broker, for example `MyParcel.com`."
      },
      "post": {
        "tags": [
          "Brokers"
        ],
        "security": [
          {
            "OAuth2": [
              "enterprises.manage"
            ]
          }
        ],
        "summary": "Create a new broker.",
        "description": "This endpoint creates a new broker with the posted data."
      }
    },
    "/brokers/{broker_id}": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          },
          {
            "OAuth2": [
              "enterprises.manage"
            ]
          }
        ],
        "summary": "Get a broker by ID.",
        "description": "This endpoint retrieves the broker with the supplied ID."
      },
      "patch": {
        "tags": [
          "Brokers"
        ],
        "security": [
          {
            "OAuth2": [
              "enterprises.manage"
            ]
          }
        ],
        "summary": "Update a broker by ID.",
        "description": "This endpoint updates the broker with the supplied ID."
      }
    },
    "/brokers/{broker_id}/carriers": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          },
          {
            "OAuth2": [
              "enterprise.manage"
            ]
          }
        ],
        "summary": "Get the available carriers for a specific broker.",
        "description": "This endpoint retrieves available carriers for a broker with the supplied ID."
      }
    },
    "/brokers/{broker_id}/relationships/carriers": {
      "post": {
        "tags": [
          "Brokers"
        ],
        "security": [
          {
            "OAuth2": [
              "enterprise.manage"
            ]
          }
        ],
        "summary": "Add carrier relationships to a broker.",
        "description": "This endpoint adds carrier relationships to the broker with the supplied ID."
      },
      "delete": {
        "tags": [
          "Brokers"
        ],
        "security": [
          {
            "OAuth2": [
              "enterprise.manage"
            ]
          }
        ],
        "summary": "Delete carrier relationships from a broker.",
        "description": "This endpoint deletes carrier relationships from the broker with the supplied ID."
      }
    },
    "/calculate-landed-costs": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "landed_cost"
            ]
          }
        ],
        "summary": "Calculate landed costs.",
        "description": "This endpoint returns the landed costs for the supplied products."
      }
    },
    "/carriers": {
      "get": {
        "tags": [
          "Carriers"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          }
        ],
        "summary": "Get all available carriers.",
        "description": "This endpoint retrieves carriers available to your API client. The availability of carriers depends on the broker your client is connected to."
      }
    },
    "/carriers/{carrier_id}": {
      "get": {
        "tags": [
          "Carriers"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          }
        ],
        "summary": "Get a carrier by ID.",
        "description": "This endpoint retrieves the carrier with the supplied ID."
      }
    },
    "/carriers/{carrier_id}/collection-time-slots": {
      "get": {
        "tags": [
          "Carriers"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get collection time slots from a carrier.",
        "description": "This endpoint retrieves collection time slots offered by the supplied carrier. These time slots can be used to specify the `collection_time` of a collection."
      }
    },
    "/carriers/{carrier_id}/contracts": {
      "get": {
        "tags": [
          "Carriers"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Get all the contracts for a carrier.",
        "description": "This endpoint retrieves contracts for the supplied carrier. Only active contracts with a verified status can be used to create shipments."
      }
    },
    "/carriers/{carrier_id}/pickup-dropoff-locations/{pudo_id}": {
      "get": {
        "tags": [
          "Carriers"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get a location from a carrier by ID.",
        "description": "This endpoint retrieves the pick-up and drop-off location with the supplied ID."
      }
    },
    "/carriers/{carrier_id}/pickup-dropoff-locations/{latitude}/{longitude}": {
      "get": {
        "tags": [
          "Carriers"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get locations from a carrier by geolocation.",
        "description": "This endpoint retrieves pick-up and drop-off locations by geolocation offered by the supplied carrier.<ul><li>Locations of the type `pick-up` can be used with services offering this as their `delivery_method`.</li><li>Locations of the type `drop-off` can be used with services offering this as their `handover_method`.</li></ul>"
      }
    },
    "/carriers/{carrier_id}/pickup-dropoff-locations/{country_code}/{postal_code}": {
      "get": {
        "tags": [
          "Carriers"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get locations from a carrier by country and postal code.",
        "description": "This endpoint retrieves pick-up and drop-off locations by country code and postal code offered by the supplied carrier.<ul><li>Locations of the type `pick-up` can be used with services offering this as their `delivery_method`.</li><li>Locations of the type `drop-off` can be used with services offering this as their `handover_method`.</li></ul>"
      }
    },
    "/carrier-surcharges": {
      "get": {
        "tags": [
          "CarrierSurcharges"
        ],
        "security": [
          {
            "OAuth2": [
              "finance.manage"
            ]
          }
        ],
        "summary": "Get all carrier surcharges.",
        "description": "This endpoint retrieves all carrier surcharges."
      },
      "post": {
        "tags": [
          "CarrierSurcharges"
        ],
        "security": [
          {
            "OAuth2": [
              "finance.manage"
            ]
          }
        ],
        "summary": "Create a new carrier surcharge.",
        "description": "This endpoint creates a new carrier surcharge with the posted data. It is required that a carrier relationship is always provided when creating a carrier surcharge."
      }
    },
    "/carrier-surcharges/{carrier_surcharge_id}": {
      "get": {
        "tags": [
          "CarrierSurcharges"
        ],
        "security": [
          {
            "OAuth2": [
              "finance.manage"
            ]
          }
        ],
        "summary": "Get a carrier surcharge by ID.",
        "description": "This endpoint retrieves the carrier surcharge with the supplied ID."
      },
      "patch": {
        "tags": [
          "CarrierSurcharges"
        ],
        "security": [
          {
            "OAuth2": [
              "finance.manage"
            ]
          }
        ],
        "summary": "Update a carrier surcharge by ID.",
        "description": "This endpoint updates the carrier surcharge with the supplied ID."
      },
      "delete": {
        "tags": [
          "CarrierSurcharges"
        ],
        "security": [
          {
            "OAuth2": [
              "finance.manage"
            ]
          }
        ],
        "summary": "Delete a carrier surcharge by ID.",
        "description": "This endpoint deletes the carrier surcharge with the supplied ID."
      }
    },
    "/clients": {
      "get": {
        "tags": [
          "Clients"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Get all available clients.",
        "description": "This endpoint retrieves all clients available to you."
      },
      "post": {
        "tags": [
          "Clients"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Create a new client.",
        "description": "This endpoint creates a new client with the posted data. The `owner` relationship will be automatically set to your user."
      }
    },
    "/clients/{client_id}": {
      "get": {
        "tags": [
          "Clients"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Get a client by ID.",
        "description": "This endpoint retrieves the client with the supplied ID."
      },
      "delete": {
        "tags": [
          "Clients"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Delete a client by ID.",
        "description": "This endpoint deletes the client with the supplied ID."
      }
    },
    "/collections": {
      "get": {
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "OAuth2": [
              "collections.manage"
            ]
          },
          {
            "OAuth2": [
              "collections.view"
            ]
          }
        ],
        "summary": "Get all available collections.",
        "description": "This endpoint retrieves collections available to your API client."
      },
      "post": {
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "OAuth2": [
              "collections.manage"
            ]
          }
        ],
        "summary": "Create a new collection.",
        "description": "This endpoint creates a new collection with the posted data."
      }
    },
    "/collections/{collection_id}": {
      "get": {
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a collection by ID.",
        "description": "This endpoint retrieves the collection with the supplied ID."
      },
      "patch": {
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "OAuth2": [
              "collections.manage"
            ]
          }
        ],
        "summary": "Update a collection by ID.",
        "description": "This endpoint updates the collection with the supplied ID. <br> The collection can be registered with the carrier through this endpoint by using the `register` attribute. <br> No further updates are possible after registration."
      },
      "delete": {
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Delete a collection by ID.",
        "description": "This endpoint deletes the collection with the supplied ID."
      }
    },
    "/collections/{collection_id}/files/{file_id}": {
      "get": {
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "OAuth2": [
              "collections.manage"
            ]
          },
          {
            "OAuth2": [
              "collections.view"
            ]
          }
        ],
        "summary": "Get a file related to a collection.",
        "description": "This endpoint retrieves a file of the supplied collection."
      }
    },
    "/collection-schedules": {
      "get": {
        "tags": [
          "CollectionSchedules"
        ],
        "security": [
          {
            "OAuth2": [
              "collections.manage"
            ]
          }
        ],
        "summary": "Get all available collection schedules.",
        "description": "This endpoint retrieves collection schedules."
      },
      "post": {
        "tags": [
          "CollectionSchedules"
        ],
        "security": [
          {
            "OAuth2": [
              "collections.manage"
            ]
          }
        ],
        "summary": "Create a new collection schedules.",
        "description": "This endpoint creates a new collection schedules."
      }
    },
    "/collection-schedules/{collection_schedule_id}": {
      "get": {
        "tags": [
          "CollectionSchedules"
        ],
        "security": [
          {
            "OAuth2": [
              "collections.manage"
            ]
          }
        ],
        "summary": "Get a collection schedule by ID.",
        "description": "This endpoint retrieves a collection schedule by ID."
      },
      "delete": {
        "tags": [
          "CollectionSchedules"
        ],
        "security": [
          {
            "OAuth2": [
              "collections.manage"
            ]
          }
        ],
        "summary": "Delete a collection schedule by ID.",
        "description": "This endpoint deletes a collection schedule by ID."
      }
    },
    "/consolidate-shipments": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Consolidate shipments.",
        "description": "This endpoint links the provided shipments to a consolidation shipment."
      }
    },
    "/contracts": {
      "get": {
        "tags": [
          "Contracts"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all available contracts.",
        "description": "This endpoint retrieves contracts available to your API client. Only active contracts with a verified status can be used to create shipments."
      },
      "post": {
        "tags": [
          "Contracts"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Create a new contract.",
        "description": "This endpoint creates a new contract with the posted data. Use your organization ID in the owner relationship to become the contract owner. The status will be `pending` until our system has checked if the credentials are valid."
      }
    },
    "/contracts/{contract_id}": {
      "get": {
        "tags": [
          "Contracts"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a contract by ID.",
        "description": "This endpoint retrieves a contract for the supplied ID."
      },
      "patch": {
        "tags": [
          "Contracts"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Update a contract by ID.",
        "description": "This endpoint updates the contract with the supplied ID. The status will be `pending` until our system has checked if the credentials are valid."
      },
      "delete": {
        "tags": [
          "Contracts"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Delete a contract by ID.",
        "description": "This endpoint deletes the contract with the supplied ID."
      }
    },
    "/contracts/{contract_id}/validate": {
      "post": {
        "tags": [
          "Contracts"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "organizations.manage"
            ]
          }
        ],
        "summary": "Validate a contract.",
        "description": "This `RPC` endpoint allows a user to re-validate a contract without changing its credentials."
      }
    },
    "/combine-files": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Create a combined file.",
        "description": "This endpoint creates a new combined file with the posted data and files."
      }
    },
    "/combined-files": {
      "get": {
        "deprecated": true,
        "tags": [
          "CombinedFiles"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all the combined files.",
        "description": "This endpoint retrieves all the combined files you have requested."
      },
      "post": {
        "deprecated": true,
        "tags": [
          "CombinedFiles"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Create a combined file.",
        "description": "This endpoint creates a new combined file with the posted data and files."
      }
    },
    "/combined-files/{combined_file_id}": {
      "get": {
        "deprecated": true,
        "tags": [
          "CombinedFiles"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a combined file  by ID.",
        "description": "This endpoint retrieves a combined file with the supplied ID."
      }
    },
    "/create-manifest-for-collection": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Generate a manifest for a collection.",
        "description": "This endpoint generates a manifest for the collection given in the request body."
      }
    },
    "/enterprises": {
      "get": {
        "tags": [
          "Enterprises"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          },
          {
            "OAuth2": [
              "enterprises.manage"
            ]
          }
        ],
        "summary": "Get all available enterprises.",
        "description": "This endpoint retrieves enterprises available to your API client."
      }
    },
    "/enterprises/{enterprise_id}": {
      "get": {
        "tags": [
          "Enterprises"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          },
          {
            "OAuth2": [
              "enterprises.manage"
            ]
          }
        ],
        "summary": "Get an enterprise by ID.",
        "description": "This endpoint retrieves the enterprise with the supplied ID."
      }
    },
    "/request-rates-template": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "contracts.manage"
            ]
          }
        ],
        "summary": "Request rates template export.",
        "description": "This endpoint queues a job to create a rates template (CSV) based on existing service rates. The template can be downloaded on completion using the `/download-rates-template` endpoint."
      }
    },
    "/download-rates-template": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "contracts.manage"
            ]
          }
        ],
        "summary": "Download rates template export.",
        "description": "This endpoint retrieves a rates template (CSV), which can be used to edit existing and add new service rates into the system."
      }
    },
    "/files/{file_id}": {
      "get": {
        "tags": [
          "Files"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a file by ID.",
        "description": "This endpoint retrieves the file with the supplied ID. Accept headers can be used to retrieve the file in a different format."
      }
    },
    "/get-carrier-status-categories": {
      "get": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get carrier status categories.",
        "description": "This endpoint retrieves a list of all possible categories of carrier-statuses. The codes can be used to populate the `filter[carrier_status][category]` query parameter on the shipments endpoint."
      }
    },
    "/get-dynamic-service-rates": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get dynamic service rates.",
        "description": "This endpoint retrieves service rates from the carrier using the specified shipment. A service and contract are required to know which carrier to communicate with."
      }
    },
    "/hooks": {
      "get": {
        "tags": [
          "Hooks"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all available hooks.",
        "description": "This endpoint retrieves hooks available to your API client."
      },
      "post": {
        "tags": [
          "Hooks"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Create a new hook.",
        "description": "This endpoint creates a new hook with the posted data."
      }
    },
    "/hooks/{hook_id}": {
      "get": {
        "tags": [
          "Hooks"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a hook by ID.",
        "description": "This endpoint retrieves the hook with the supplied ID."
      },
      "patch": {
        "tags": [
          "Hooks"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Update a hook by ID.",
        "description": "This endpoint updates the hook with the supplied ID."
      },
      "delete": {
        "tags": [
          "Hooks"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Delete a hook by ID.",
        "description": "This endpoint deletes the hook with the supplied ID."
      }
    },
    "/hooks/{hook_id}/logs": {
      "get": {
        "tags": [
          "Hooks"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all the logs for a hook.",
        "description": "This endpoint retrieves logs for the supplied hook."
      }
    },
    "/hook-logs/{hook_log_id}": {
      "get": {
        "tags": [
          "HookLogs"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a hook log by ID.",
        "description": "This endpoint retrieves the hook log with the supplied ID."
      }
    },
    "/integrations": {
      "get": {
        "tags": [
          "Integrations"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get all the integrations.",
        "description": "This endpoint retrieves the available integrations in the MyParcel.com API."
      }
    },
    "/integrations/{integration_id}": {
      "get": {
        "tags": [
          "Integrations"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get an integration by ID.",
        "description": "This endpoint retrieves the integration with the supplied ID."
      }
    },
    "/invoices": {
      "get": {
        "tags": [
          "Invoices"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get all available invoices.",
        "description": "This endpoint retrieves invoices available to your API client."
      },
      "post": {
        "tags": [
          "Invoices"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Create a new invoice.",
        "description": "This endpoint creates a new invoice with the posted data."
      }
    },
    "/invoices/{invoice_id}": {
      "get": {
        "tags": [
          "Invoices"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get one invoice.",
        "description": "This endpoint retrieves the invoice with the supplied ID."
      },
      "patch": {
        "tags": [
          "Invoices"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Update an invoice by ID.",
        "description": "This endpoint updates the invoice with the supplied ID."
      }
    },
    "/liability-coverages/{liability_coverage_id}": {
      "get": {
        "tags": [
          "LiabilityCoverages"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a liability coverage by ID.",
        "description": "This endpoint retrieves a liability coverage for the supplied ID."
      }
    },
    "/locales/v1/locales": {
      "get": {
        "tags": [
          "Locales"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Get all locales.",
        "description": "This endpoint retrieves all locales."
      }
    },
    "/manifests": {
      "get": {
        "tags": [
          "Manifests"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all available manifests.",
        "description": "This endpoint retrieves manifests available to your API client."
      },
      "post": {
        "tags": [
          "Manifests"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Create a new manifest.",
        "description": "This endpoint creates a new manifest with the posted data."
      }
    },
    "/manifests/{manifest_id}": {
      "get": {
        "tags": [
          "Manifests"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a manifest by ID.",
        "description": "This endpoint retrieves the manifest with the supplied ID."
      }
    },
    "/manifests/{manifest_id}/files/{file_id}": {
      "get": {
        "tags": [
          "Manifests"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a file related to a manifest.",
        "description": "This endpoint retrieves a file of the supplied manifest."
      }
    },
    "/onboarding/v1/invitations": {
      "get": {
        "tags": [
          "Invitations"
        ],
        "security": [
          {
            "OAuth2": [
              "brokers.manage"
            ]
          }
        ],
        "summary": "Get all available invitations.",
        "description": "This endpoint retrieves invitations available to your API client."
      },
      "post": {
        "tags": [
          "Invitations"
        ],
        "security": [
          {
            "OAuth2": [
              "brokers.manage"
            ]
          }
        ],
        "summary": "Create a new invitation.",
        "description": "This endpoint creates a new invitation with the posted data."
      }
    },
    "/onboarding/v1/invitations/{invitation_id}": {
      "get": {
        "tags": [
          "Invitations"
        ],
        "security": [
          {
            "OAuth2": [
              "brokers.manage"
            ]
          }
        ],
        "summary": "Get an invitation resource.",
        "description": "This endpoint retrieves a invitation resource by the specified ID."
      }
    },
    "/onboarding/v1/invitations/{invitation_id}/onboard": {
      "post": {
        "tags": [
          "Invitations"
        ],
        "security": [
          {
            "OAuth2": [
              "brokers.manage"
            ]
          }
        ],
        "summary": "Start onboarding process.",
        "description": "This `RPC` endpoint creates a user based on an invitation."
      }
    },
    "/organizations": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all available organizations.",
        "description": "This endpoint retrieves organizations available to your API client."
      },
      "post": {
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          }
        ],
        "summary": "Create a new organization.",
        "description": "This endpoint creates a new organization with the posted data."
      }
    },
    "/organizations/{organization_id}": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.view"
            ]
          }
        ],
        "summary": "Get an organization by ID.",
        "description": "This endpoint retrieves the organization with the supplied ID."
      },
      "patch": {
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Update an organization by ID.",
        "description": "This endpoint updates the organization with the supplied ID."
      },
      "delete": {
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Delete an organization by ID.",
        "description": "This endpoint deletes the organization with the supplied ID."
      }
    },
    "/organizations/{organization_id}/contracts": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Get the available contracts for a specific organization.",
        "description": "This endpoint retrieves available contracts for an organization with the supplied ID."
      }
    },
    "/organizations/{organization_id}/relationships/contracts": {
      "post": {
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "contracts.manage",
              "organizations.manage"
            ]
          }
        ],
        "summary": "Add contract relationships to an organization.",
        "description": "This endpoint adds contract relationships to the organization with the supplied ID."
      },
      "delete": {
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "OAuth2": [
              "contracts.manage",
              "organizations.manage"
            ]
          }
        ],
        "summary": "Delete contract relationships from an organization.",
        "description": "This endpoint deletes contract relationships from the organization with the supplied ID."
      }
    },
    "/password-resets": {
      "post": {
        "tags": [
          "PasswordResets"
        ],
        "summary": "Create a password reset.",
        "description": "This endpoint creates a new password reset with the posted data. <strong>A password reset link will be sent via email.</strong> Any previous password resets for this user will be disabled."
      }
    },
    "/password-resets/{password_reset_id}": {
      "patch": {
        "tags": [
          "PasswordResets"
        ],
        "summary": "Update a password reset by ID.",
        "description": "This endpoint updates the password reset with the supplied ID. As a result, the password of the user will be updated."
      }
    },
    "/rate-imports": {
      "get": {
        "tags": [
          "RateImports"
        ],
        "security": [
          {
            "OAuth2": [
              "contracts.manage"
            ]
          }
        ],
        "summary": "Get all rate imports.",
        "description": "This endpoint retrieves rate imports available to your API client."
      },
      "post": {
        "tags": [
          "RateImports"
        ],
        "security": [
          {
            "OAuth2": [
              "contracts.manage"
            ]
          }
        ],
        "summary": "Create a new rate import.",
        "description": "This endpoint creates a new rate import with the posted data."
      }
    },
    "/rate-imports/{rate_import_id}": {
      "get": {
        "tags": [
          "RateImports"
        ],
        "security": [
          {
            "OAuth2": [
              "contracts.manage"
            ]
          }
        ],
        "summary": "Get a rate import by ID.",
        "description": "This endpoint retrieves the rate import with the supplied ID."
      }
    },
    "/regions": {
      "get": {
        "deprecated": true,
        "tags": [
          "Regions"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get all the regions.",
        "description": "This endpoint retrieves regions. All regions are connected via parent-child relationships. Services are available in certain regions. Regions with a country code can be used to create shipments."
      }
    },
    "/regions/{region_id}": {
      "get": {
        "deprecated": true,
        "tags": [
          "Regions"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get a region by ID.",
        "description": "This endpoint retrieves the region with the supplied ID."
      }
    },
    "/reports": {
      "get": {
        "tags": [
          "Reports"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all reports available to you.",
        "description": "This endpoint retrieves all reports available to you."
      },
      "post": {
        "tags": [
          "Reports"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Create a new report.",
        "description": "This endpoint creates a new report based on the posted filters."
      }
    },
    "/reports/{report_id}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a report by ID.",
        "description": "This endpoint retrieves the report with the supplied ID."
      },
      "delete": {
        "tags": [
          "Reports"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Delete a report by ID.",
        "description": "This endpoint deletes the report with the supplied ID."
      }
    },
    "/reports/{report_id}/files/{file_id}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a file related to a report.",
        "description": "This endpoint retrieves the file of the supplied report. All successfully completed reports will have an attached CSV file."
      }
    },
    "/returns/v1/demo-orders": {
      "get": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get all demo orders resources.",
        "description": "This endpoint retrieves generated orders to test creating returns."
      },
      "post": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Create a new demo order.",
        "description": "This endpoint creates a new demo order with the posted data."
      }
    },
    "/returns/v1/demo-orders/{demo_order_id}": {
      "get": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get a demo order resource.",
        "description": "This endpoint retrieves a demo order resource by the specified ID."
      }
    },
    "/returns/v1/returns": {
      "get": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get all available returns.",
        "description": "This endpoint retrieves returns available to your API client."
      },
      "post": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Create a new return.",
        "description": "This endpoint creates a new return with the posted data."
      }
    },
    "/returns/v1/returns/{return_id}": {
      "get": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get a return resource.",
        "description": "This endpoint retrieves a return resource by the specified ID."
      }
    },
    "/returns/v1/returns/{return_id}/approve": {
      "post": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Approve a return.",
        "description": "This endpoint modifies the status of a return resource to `return-approved`"
      }
    },
    "/returns/v1/returns/{return_id}/reject": {
      "post": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Reject a return.",
        "description": "This endpoint modifies the status of a return resource to `return-rejected`"
      }
    },
    "/returns/v1/returns/{return_id}/request-payment": {
      "post": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Request a payment for a return.",
        "description": "This endpoint requests a payment for a return through the connected payment provider"
      }
    },
    "/returns/v1/returns/{return_id}/request-recovery-shipment": {
      "post": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Request a recovery shipment for a return.",
        "description": "This endpoint generates a recovery shipment for a return. This serves as a fallback for when the shipment label of the primary return method cannot be used, for example due to a damaged or missing label that was in the parcel."
      }
    },
    "/returns/v1/returns/{return_id}/payment-checkout-url/{payment_id}?hmac={hmac}": {
      "get": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get a return payment checkout url",
        "description": "This endpoint requests a return payment checkout url to a payment provider"
      }
    },
    "/returns/v1/returns/{return_id}/retry-shipment": {
      "post": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Retry shipment registration on a return.",
        "description": "This endpoint allows the API user to manually trigger shipment registration on a return."
      }
    },
    "/returns/v1/return-methods": {
      "get": {
        "tags": [
          "ReturnMethods"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get all available return methods.",
        "description": "This endpoint retrieves return methods available to your API client."
      },
      "post": {
        "tags": [
          "ReturnMethods"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Create a new return method.",
        "description": "This endpoint creates a new return method with the posted data."
      }
    },
    "/returns/v1/return-methods/{return_method_id}": {
      "get": {
        "tags": [
          "ReturnMethods"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get a return method resource.",
        "description": "This endpoint retrieves a return method resource by the specified ID."
      },
      "delete": {
        "tags": [
          "ReturnMethods"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Delete a return method by ID.",
        "description": "This endpoint deletes the return method with the supplied ID."
      }
    },
    "/returns/v1/reasons": {
      "get": {
        "tags": [
          "ReturnReasons"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "return_reasons.manage"
            ]
          }
        ],
        "summary": "Get all available return reasons.",
        "description": "This endpoint retrieves returns reasons available to your API client."
      },
      "post": {
        "tags": [
          "ReturnReasonsManagement"
        ],
        "security": [
          {
            "OAuth2": [
              "return_reasons.manage"
            ]
          }
        ],
        "summary": "Create a new return reason.",
        "description": "This endpoint creates a new return reason with the posted data."
      }
    },
    "/returns/v1/reasons/{return_reason_id}": {
      "get": {
        "tags": [
          "ReturnReasons"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "return_reasons.manage"
            ]
          }
        ],
        "summary": "Retrieve a return reason by ID.",
        "description": "This endpoint retrieves the return reason with the supplied ID."
      },
      "patch": {
        "tags": [
          "ReturnReasonsManagement"
        ],
        "security": [
          {
            "OAuth2": [
              "return_reasons.manage"
            ]
          }
        ],
        "summary": "Update a return reason by ID.",
        "description": "This endpoint updates the return reason with the supplied ID."
      },
      "delete": {
        "tags": [
          "ReturnReasonsManagement"
        ],
        "security": [
          {
            "OAuth2": [
              "return_reasons.manage"
            ]
          }
        ],
        "summary": "Delete a return reason by ID.",
        "description": "This endpoint deletes the return reason with the supplied ID."
      }
    },
    "/returns/v1/shops/{shop_id}/orders/{reference}/{email}": {
      "get": {
        "tags": [
          "Returns"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get an order resource.",
        "description": "This endpoint retrieves an order resource by the specified reference and email address."
      }
    },
    "/returns/v1/shops/{shop_id}/reasons": {
      "get": {
        "tags": [
          "ReturnReasons"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get all return reasons for the given shop.",
        "description": "This endpoint retrieves return reasons for the given shop."
      },
      "post": {
        "tags": [
          "ReturnReasons"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Link return reasons to the given shop.",
        "description": "This endpoint links return reasons to the specified shop."
      }
    },
    "/returns/v1/shops/{shop_id}/reasons/{return_reason_id}": {
      "delete": {
        "tags": [
          "ReturnReasons"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Delete return reason from shop.",
        "description": "This endpoint deletes a return reason from the shop."
      }
    },
    "/returns/v1/shops/{shop_id}/reasons/{return_reason_id}/set-questions": {
      "post": {
        "tags": [
          "ReturnQuestions"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Link return questions to a shop's return reason.",
        "description": "This endpoint links return questions to the specified shop's return reason. It overrides previously linked return questions."
      }
    },
    "/returns/v1/analytics/approved": {
      "get": {
        "tags": [
          "ReturnAnalytics"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get histogram of approved returns.",
        "description": "This endpoint retrieves the amount of approved returns per date."
      }
    },
    "/returns/v1/analytics/most-returned-items": {
      "get": {
        "tags": [
          "ReturnAnalytics"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get the most returned items.",
        "description": "This endpoint retrieves the most returned items and their return reasons."
      }
    },
    "/returns/v1/analytics/orders": {
      "get": {
        "tags": [
          "ReturnAnalytics"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get histogram of marketplace orders count.",
        "description": "This endpoint retrieves the number of orders per date interval (day or month)."
      }
    },
    "/returns/v1/questions": {
      "get": {
        "tags": [
          "ReturnQuestions"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "return_questions.manage"
            ]
          }
        ],
        "summary": "Get all available return questions.",
        "description": "This endpoint retrieves return questions available to your API client."
      },
      "post": {
        "tags": [
          "ReturnQuestions"
        ],
        "security": [
          {
            "OAuth2": [
              "return_questions.manage"
            ]
          }
        ],
        "summary": "Create a new return question.",
        "description": "This endpoint creates a new return question with the posted data."
      }
    },
    "/returns/v1/questions/{return_question_id}": {
      "get": {
        "tags": [
          "ReturnQuestions"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "return_questions.manage"
            ]
          }
        ],
        "summary": "Retrieve a return question by ID.",
        "description": "This endpoint retrieves the return question with the supplied ID."
      },
      "patch": {
        "tags": [
          "ReturnQuestions"
        ],
        "security": [
          {
            "OAuth2": [
              "return_questions.manage"
            ]
          }
        ],
        "summary": "Update a return question by ID.",
        "description": "This endpoint updates the return question with the supplied ID."
      },
      "delete": {
        "tags": [
          "ReturnQuestions"
        ],
        "security": [
          {
            "OAuth2": [
              "return_questions.manage"
            ]
          }
        ],
        "summary": "Delete a return question by ID.",
        "description": "This endpoint deletes the return question with the supplied ID."
      }
    },
    "/returns/v1/reports": {
      "get": {
        "tags": [
          "ReturnReports"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get all return reports available to you.",
        "description": "This endpoint retrieves all return reports available to you."
      },
      "post": {
        "tags": [
          "ReturnReports"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Create a new return report.",
        "description": "This endpoint creates a new return report based on the posted filters."
      }
    },
    "/returns/v1/reports/count-report-entries": {
      "post": {
        "tags": [
          "ReturnReports"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get projected return report entries count.",
        "description": "This endpoint retrieves the number of return report entries that would be included in a report with the supplied filters."
      }
    },
    "/returns/v1/reports/{report_id}": {
      "get": {
        "tags": [
          "ReturnReports"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get a return report by ID.",
        "description": "This endpoint retrieves the return report with the supplied ID."
      },
      "delete": {
        "tags": [
          "ReturnReports"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Delete a return report by ID.",
        "description": "This endpoint deletes the report with the supplied ID."
      }
    },
    "/returns/v1/reports/{report_id}/files/{file_id}": {
      "get": {
        "tags": [
          "ReturnReports"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          }
        ],
        "summary": "Get a file related to a return report.",
        "description": "This endpoint retrieves the file of the supplied return report. All successfully completed reports will have an attached CSV file."
      }
    },
    "/scopes": {
      "get": {
        "tags": [
          "Scopes"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get all the scopes.",
        "description": "This endpoint retrieves all available scopes. Scopes are used to give users access to API endpoints."
      }
    },
    "/scopes/{scope_id}": {
      "get": {
        "tags": [
          "Scopes"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get a scope by ID.",
        "description": "This endpoint retrieves the scope with the supplied ID."
      }
    },
    "/services": {
      "get": {
        "tags": [
          "Services"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          }
        ],
        "summary": "Get all available services.",
        "description": "This endpoint retrieves services available to your API client."
      }
    },
    "/services/{service_id}": {
      "get": {
        "tags": [
          "Services"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          }
        ],
        "summary": "Get a service by ID.",
        "description": "This endpoint retrieves the service with the supplied ID."
      }
    },
    "/service-rates": {
      "get": {
        "tags": [
          "ServiceRates"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get all available service rates.",
        "description": "This endpoint retrieves service rates available to your API client."
      },
      "post": {
        "tags": [
          "ServiceRates"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Create a new service rate.",
        "description": "This endpoint creates a new service rate from the posted data."
      }
    },
    "/service-rates/{service_rate_id}": {
      "get": {
        "tags": [
          "ServiceRates"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get a service rate by ID.",
        "description": "This endpoint retrieves a service rate with the supplied ID."
      },
      "patch": {
        "tags": [
          "ServiceRates"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Update a service rate by ID.",
        "description": "This endpoint updates the service rate with the supplied ID."
      }
    },
    "/service-options": {
      "get": {
        "tags": [
          "ServiceOptions"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get all available service options.",
        "description": "This endpoint retrieves service options available to your API client."
      }
    },
    "/service-options/{service_option_id}": {
      "get": {
        "tags": [
          "ServiceOptions"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get a service option by ID.",
        "description": "This endpoint retrieves a service option with the supplied ID."
      }
    },
    "/shipments": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all available shipments.",
        "description": "This endpoint retrieves shipments available to your API client."
      },
      "post": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Create a new shipment.",
        "description": "This endpoint creates a new shipment with the posted data."
      }
    },
    "/registered-shipments": {
      "post": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Create a new shipment which is immediately registered with the carrier.",
        "description": "This endpoint creates a new shipment with the posted data, which is then immediately communicated to the carrier. The carrier response is processed before your request is completed, so files will be available."
      }
    },
    "/multi-colli-shipments": {
      "post": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Create and register a multi-colli shipment.",
        "description": "This endpoint creates a new shipment consisting of multiple parcels to the same address, which is then immediately communicated to the carrier. The carrier response is processed before your request is completed, so files will be available."
      }
    },
    "/payments/v1/providers/{code}/connect": {
      "post": {
        "tags": [
          "PaymentProviders"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Connect to a payment provider.",
        "description": "This endpoint connects a payment provider to your shop."
      }
    },
    "/payments/v1/providers/{code}/disconnect": {
      "post": {
        "tags": [
          "PaymentProviders"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Disconnect your shop from a payment provider.",
        "description": "This endpoint revokes access to from your shop to a payment provider."
      }
    },
    "/payments/v1/providers": {
      "get": {
        "tags": [
          "PaymentProviders"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Get all payment providers.",
        "description": "This endpoint retrieves payment providers available to your API client."
      }
    },
    "/shipments/{shipment_id}": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a shipment by ID.",
        "description": "This endpoint retrieves the shipment with the supplied ID."
      },
      "patch": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Update a shipment by ID.",
        "description": "This endpoint updates the shipment with the supplied ID."
      },
      "delete": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Delete a shipment by ID.",
        "description": "This endpoint deletes the shipment with the supplied ID."
      }
    },
    "/shipments/{shipment_id}/files": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all the files from a shipment.",
        "description": "This endpoint retrieves files for the supplied shipment. All successfully registered shipments will have a `label` file. International shipments with customs information will have extra files."
      }
    },
    "/shipments/{shipment_id}/statuses": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all the statuses from a shipment.",
        "description": "This endpoint retrieves statuses for the supplied shipment."
      }
    },
    "/shipments/{shipment_id}/statuses/{shipment_status_id}": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a shipment status by ID.",
        "description": "This endpoint retrieves the shipment status with the supplied ID."
      }
    },
    "/shipments/{shipment_id}/surcharges": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all surcharges related to a shipment.",
        "description": "This endpoint retrieves surcharges for the supplied shipment."
      }
    },
    "/shipments/{shipment_id}/surcharges/{shipment_surcharge_id}": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a shipment surcharge by ID.",
        "description": "This endpoint retrieves the shipment surcharge with the supplied ID."
      }
    },
    "/shipment-surcharges": {
      "get": {
        "tags": [
          "ShipmentSurcharges"
        ],
        "security": [
          {
            "OAuth2": [
              "finance.manage"
            ]
          }
        ],
        "summary": "Get all surcharges across all shipments.",
        "description": "This endpoint retrieves all surcharges for all shipments."
      },
      "post": {
        "tags": [
          "ShipmentSurcharges"
        ],
        "security": [
          {
            "OAuth2": [
              "finance.manage"
            ]
          }
        ],
        "summary": "Create a new shipment surcharge.",
        "description": "This endpoint creates a new shipment surcharge with the posted data. It is required that a shipment relationship is always provided when creating a shipment surcharge."
      }
    },
    "/shipment-surcharges/{shipment_surcharge_id}": {
      "get": {
        "tags": [
          "ShipmentSurcharges"
        ],
        "security": [
          {
            "OAuth2": [
              "finance.manage"
            ]
          }
        ],
        "summary": "Get a shipment surcharge by ID.",
        "description": "This endpoint retrieves the shipment surcharge with the supplied ID."
      },
      "patch": {
        "tags": [
          "ShipmentSurcharges"
        ],
        "security": [
          {
            "OAuth2": [
              "finance.manage"
            ]
          }
        ],
        "summary": "Update a shipment surcharge by ID.",
        "description": "This endpoint updates the shipment surcharge with the supplied ID."
      },
      "delete": {
        "tags": [
          "ShipmentSurcharges"
        ],
        "security": [
          {
            "OAuth2": [
              "finance.manage"
            ]
          }
        ],
        "summary": "Delete a shipment surcharge by ID.",
        "description": "This endpoint deletes the shipment surcharge with the supplied ID."
      }
    },
    "/shops": {
      "get": {
        "tags": [
          "Shops"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "returns.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.view"
            ]
          }
        ],
        "summary": "Get all available shops.",
        "description": "This endpoint retrieves shops available to your API client."
      },
      "post": {
        "tags": [
          "Shops"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Create a new shop.",
        "description": "This endpoint creates a new shop with the posted data."
      }
    },
    "/shops/{shop_id}": {
      "get": {
        "tags": [
          "Shops"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "broker.member",
              "shipments.view"
            ]
          }
        ],
        "summary": "Get a shop by ID.",
        "description": "This endpoint retrieves the shop with the supplied ID."
      },
      "patch": {
        "tags": [
          "Shops"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Update a shop by ID.",
        "description": "This endpoint updates the shop with the supplied ID."
      },
      "delete": {
        "tags": [
          "Shops"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Delete a shop by ID.",
        "description": "This endpoint deletes the shop with the supplied ID."
      }
    },
    "/shops/{shop_id}/integrations": {
      "get": {
        "tags": [
          "Shops"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get the integration resources related to this shop.",
        "description": "This endpoint retrieves the integration resources related to the shop with the supplied ID."
      }
    },
    "/shops/{shop_id}/integrations/{integration_id}/shipments": {
      "get": {
        "tags": [
          "Shops"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get shipments from integration",
        "description": "This endpoint connects to an external integration and requests shipment data for a specified time period."
      }
    },
    "/shops/{shop_id}/relationships/integrations": {
      "get": {
        "tags": [
          "Shops"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get the integration relationships for a shop ID.",
        "description": "This endpoint retrieves the integration relationships for the supplied shop ID."
      },
      "post": {
        "tags": [
          "Shops"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Add integration relationships to the shop.",
        "description": "This endpoint adds integration relationships for the shop with the supplied ID."
      },
      "delete": {
        "tags": [
          "Shops"
        ],
        "security": [
          {
            "OAuth2": [
              "organizations.manage"
            ]
          }
        ],
        "summary": "Delete integration relationships from a shop.",
        "description": "This endpoint deletes integration relationships from the shop with the supplied ID."
      }
    },
    "/statuses": {
      "get": {
        "tags": [
          "Statuses"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get all the statuses.",
        "description": "This endpoint retrieves all available statuses. Statuses can be attached to resources, for example shipment-statuses."
      }
    },
    "/statuses/{status_id}": {
      "get": {
        "tags": [
          "Statuses"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "summary": "Get a status by ID.",
        "description": "This endpoint retrieves the status with the supplied ID."
      }
    },
    "/suggest-hscode": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "landed_cost"
            ]
          }
        ],
        "summary": "Get HS code suggestions.",
        "description": "This endpoint returns Harmonized System code suggestions for the supplied product."
      }
    },
    "/system-messages": {
      "get": {
        "tags": [
          "SystemMessages"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          }
        ],
        "summary": "Get all the system messages.",
        "description": "This endpoint retrieves system messages. These are informative messages about our system or a specific type of resource."
      },
      "post": {
        "tags": [
          "SystemMessages"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "system.manage"
            ]
          }
        ],
        "summary": "Create a new system message.",
        "description": "This endpoint creates a new system message with the posted data."
      }
    },
    "/system-messages/{system_message_id}": {
      "get": {
        "tags": [
          "SystemMessages"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member"
            ]
          }
        ],
        "summary": "Get a system message by ID.",
        "description": "This endpoint retrieves the system message with the supplied ID."
      },
      "patch": {
        "tags": [
          "SystemMessages"
        ],
        "security": [
          {
            "OAuth2": [
              "broker.member",
              "system.manage"
            ]
          }
        ],
        "summary": "Update a system message by ID.",
        "description": "This endpoint updates the system message with the supplied ID."
      },
      "delete": {
        "tags": [
          "SystemMessages"
        ],
        "security": [
          {
            "OAuth2": [
              "system.manage"
            ]
          }
        ],
        "summary": "Delete a system message by ID.",
        "description": "This endpoint deletes the system message with the supplied ID."
      }
    },
    "/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": [
              "users.manage"
            ]
          },
          {
            "OAuth2": []
          }
        ],
        "summary": "Get all available users.",
        "description": "This endpoint retrieves users available to your API client."
      },
      "post": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": [
              "users.manage"
            ]
          }
        ],
        "summary": "Create a new user.",
        "description": "This endpoint creates a new user with the posted data."
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": [
              "users.manage"
            ]
          },
          {
            "OAuth2": []
          }
        ],
        "summary": "Get a user by ID.",
        "description": "This endpoint retrieves the user with the supplied ID. You can always retrieve your own user, but you need the `users.manage` scope to retrieve other users."
      },
      "patch": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": [
              "users.manage"
            ]
          },
          {
            "OAuth2": []
          }
        ],
        "summary": "Update a user by ID.",
        "description": "This endpoint updates the user with the supplied ID."
      }
    },
    "/users/{user_id}/relationships/scopes": {
      "get": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": [
              "users.manage"
            ]
          }
        ],
        "summary": "Get the scope relationships for a user ID.",
        "description": "This endpoint retrieves the scope relationships for the supplied user ID."
      },
      "post": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": [
              "users.manage"
            ]
          }
        ],
        "summary": "Add scope relationships to a user.",
        "description": "This endpoint adds scope relationships to the user with the supplied ID."
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": [
              "users.manage"
            ]
          }
        ],
        "summary": "Delete scope relationships from a user.",
        "description": "This endpoint deletes scope relationships from the user with the supplied ID."
      }
    },
    "/count-report-entries": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          },
          {
            "OAuth2": [
              "shipments.view"
            ]
          }
        ],
        "summary": "Get report size",
        "description": "This endpoint retrieves the total number of entries that will be included in a report."
      }
    },
    "/export-login-attempts": {
      "get": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "logs.view"
            ]
          }
        ],
        "summary": "Export login attempts logs in CSV format",
        "description": "This endpoint retrieves all broker-related login attempt logs in a CSV format."
      }
    },
    "/track-external-shipment": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Track external shipment.",
        "description": "This endpoint is used to track externally registered shipments to provide tracking information."
      }
    },
    "/suggest-address": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "addresses.suggest"
            ]
          }
        ],
        "summary": "Get address suggestions.",
        "description": "This endpoint returns address suggestions based on the provided address details."
      }
    },
    "/update-shipment-status": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Update the status of a shipment.",
        "description": "This endpoint allows a user to trigger a status update for a shipment. The shipment will be synchronized with the carrier.<br><br>Since our **sandbox environment** does not provide real shipments, a `status_id` can be provided to simulate a shipment status update."
      }
    },
    "/void-shipment": {
      "post": {
        "tags": [
          "RPC"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Void a registered shipment whose label is not going to be used.",
        "description": "This endpoint allows a user to void a registered shipment if it's label is not going to be used. This will avoid unused labels to be invoiced by the carrier."
      }
    },
    "/analytics/on-time-delivery/{interval}": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get analytics report for delivered shipments on time.",
        "description": "This endpoint retrieves the rate by which shipments are successfully delivered on time on intervals."
      }
    },
    "/analytics/volume/{group_by}/{interval}": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "security": [
          {
            "OAuth2": [
              "shipments.manage"
            ]
          }
        ],
        "summary": "Get analytics report for volumes per carrier.",
        "description": "This endpoint retrieves the amount of shipments delivered organized by carrier over time."
      }
    },
    "/zones": {
      "get": {
        "tags": [
          "Zones"
        ],
        "security": [
          {
            "OAuth2": [
              "contracts.manage"
            ]
          },
          {
            "OAuth2": [
              "zones.manage"
            ]
          }
        ],
        "summary": "Get all the zones.",
        "description": "This endpoint retrieves zones."
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "zones.manage"
            ]
          }
        ],
        "tags": [
          "Zones"
        ],
        "summary": "Create a new zone.",
        "description": "This endpoint creates a new zone with the posted data."
      }
    },
    "/zones/{zone_id}": {
      "get": {
        "tags": [
          "Zones"
        ],
        "security": [
          {
            "OAuth2": [
              "contracts.manage"
            ]
          },
          {
            "OAuth2": [
              "zones.manage"
            ]
          }
        ],
        "summary": "Get a zone by ID.",
        "description": "This endpoint retrieves the zone with the supplied ID."
      },
      "patch": {
        "tags": [
          "Zones"
        ],
        "security": [
          {
            "OAuth2": [
              "zones.manage"
            ]
          }
        ],
        "summary": "Update a zone by ID.",
        "description": "This endpoint updates the zone with the supplied ID."
      },
      "delete": {
        "tags": [
          "Zones"
        ],
        "security": [
          {
            "OAuth2": [
              "zones.manage"
            ]
          }
        ],
        "summary": "Delete a zone by ID.",
        "description": "This endpoint deletes the zone with the supplied ID."
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "description": "[API documentation](https://docs.myparcel.com/api/authentication.html)",
        "name": "Authorization",
        "in": "header",
        "scheme": "Bearer",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://auth.myparcel.com/access-token",
            "scopes": {
              "addresses.suggest": "Retrieve address suggestions.",
              "broker.member": "Retrieve broker related resources and create organizations for that broker.",
              "collections.manage": "Manage collection resources.",
              "collections.view": "Retrieve collection resources.",
              "contracts.manage": "Manage contract resources.",
              "enterprises.manage": "Manage enterprise related resources.",
              "finance.manage": "Manage all finance related resources.",
              "logs.view": "Retrieve audit logs on behalf of a broker.",
              "organizations.manage": "Manage organization related resources on behalf of a single organization or all organizations belonging to a broker.",
              "returns.manage": "Manage all return related resources.",
              "shipments.manage": "Manage shipments on behalf of all shops belonging to an organization or broker.",
              "shipments.view": "Retrieve shipments on behalf of all shops belonging to an organization or broker.",
              "system.manage": "Manage all system related resources.",
              "users.manage": "Manage user resources.",
              "zones.manage": "Manage zone resources."
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Addresses"
    },
    {
      "name": "Brokers"
    },
    {
      "name": "Carriers"
    },
    {
      "name": "CarrierSurcharges"
    },
    {
      "name": "Clients"
    },
    {
      "name": "Collections"
    },
    {
      "name": "CollectionSchedules"
    },
    {
      "name": "CombinedFiles"
    },
    {
      "name": "Contracts"
    },
    {
      "name": "Enterprises"
    },
    {
      "name": "Files"
    },
    {
      "name": "Hooks"
    },
    {
      "name": "HookLogs"
    },
    {
      "name": "Integrations"
    },
    {
      "name": "Invitations"
    },
    {
      "name": "Invoices"
    },
    {
      "name": "LiabilityCoverages"
    },
    {
      "name": "Locales"
    },
    {
      "name": "Manifests"
    },
    {
      "name": "Organizations"
    },
    {
      "name": "PasswordResets"
    },
    {
      "name": "PaymentProviders"
    },
    {
      "name": "RateImports"
    },
    {
      "name": "Regions"
    },
    {
      "name": "Reports"
    },
    {
      "name": "Returns"
    },
    {
      "name": "ReturnMethods"
    },
    {
      "name": "ReturnReasons"
    },
    {
      "name": "ReturnReasonsManagement"
    },
    {
      "name": "ReturnQuestions"
    },
    {
      "name": "ReturnAnalytics"
    },
    {
      "name": "ReturnReports"
    },
    {
      "name": "Scopes"
    },
    {
      "name": "Services"
    },
    {
      "name": "ServiceOptions"
    },
    {
      "name": "ServiceRates"
    },
    {
      "name": "Shipments"
    },
    {
      "name": "ShipmentSurcharges"
    },
    {
      "name": "Shops"
    },
    {
      "name": "Statuses"
    },
    {
      "name": "SystemMessages"
    },
    {
      "name": "Users"
    },
    {
      "name": "Zones"
    },
    {
      "name": "RPC"
    },
    {
      "name": "Analytics"
    }
  ]
}
