openapi: 3.0.0
info:
  title: Skrill PSD2 API
  description: API for accessing Skrill PSD2 services such as Account Information and Payment Initiation.
  version: 1.0.0
servers:
  - url: https://developer-psd2.skrill.com/api-reference

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /accounts:
    get:
      summary: Get Customer Accounts Information
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized

  /transactions/{accountId}:
    get:
      summary: Get Transaction History for a Customer Account
      security:
        - BearerAuth: []
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized

  /payments/preview:
    post:
      summary: Send Money Preview
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                currency:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized

  /payments:
    post:
      summary: Send Money
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                currency:
                  type: string
                recipient:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized

  /payments/finalize:
    post:
      summary: Finalize Money Transfer
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentId:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized

  /otp/sms:
    post:
      summary: Trigger OTP SMS Code
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneNumber:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized

  /otp/validate:
    post:
      summary: Validate OTP Code
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                otpCode:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized