openapi: 3.0.1
info:
  title: na.internal.enterprise.demoservice.1
  version: '1'
servers:
  - url: https://nauat08.chubbdigital.com/data.demoservice
  - url: https://nauat.chubbdigital.com/data.demoservice
  - url: https://dp-uat.digitalgateway.chubb.com/data.demoservice
  - url: https://mtls-uat.na.digitalgateway.chubb.com/data.demoservice
  - url: https://na-central-uat.chubbdigital.com/data.demoservice
paths:
  /caching:
    get:
      tags:
        - Demo
      summary: Caching
      description: Caching test
      operationId: Caching
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /payloadTrans:
    put:
      tags:
        - Demo
      summary: PayloadTrans
      description: PayloadTransformation test
      operationId: PayloadTrans
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitSessionBodyRequest-json'
            example: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /routing:
    get:
      tags:
        - Demo
      summary: Routing
      description: Routing test
      operationId: Routing
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /mock:
    get:
      tags:
        - Demo
      summary: mock
      description: Mocking test
      operationId: mock
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /decrypt:
    post:
      tags:
        - Demo
      summary: decrypt
      description: decrypt test
      operationId: decrypt
      parameters:
        - name: Authorization
          in: header
          description: ' JWT Bearer token for OAuth authentication'
          required: true
          schema:
            type: string
        - name: apiVersion
          in: header
          description: 'Api Version (eg :1, 2)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
components:
  schemas:
    SubmitSessionBodyRequest-json:
      type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]