openapi: 3.0.1
info:
  title: na.external.digital-sci.marketplacetoken
  description: 'Generate a bearer token using Appid, App Secret and resource to access your APIs'
  version: '2'
servers:
  - url: https://nauat08.chubbdigital.com/api/tokens
  - url: https://nauat.chubbdigital.com/api/tokens
  - url: https://dp-uat.digitalgateway.chubb.com/api/tokens
  - url: https://mtls-uat.na.digitalgateway.chubb.com/api/tokens
  - url: https://na-central-uat.chubbdigital.com/api/tokens
paths:
  /:
    post:
      summary: Token
      description: 'Generate and return an Authorization Token, to be used with all subsequent API calls.'
      operationId: token
      parameters:
        - name: App_ID
          in: header
          description: App_ID supplied by CHUBB
          required: true
          schema:
            type: string
        - name: App_Key
          in: header
          description: App_Key supplied by CHUBB
          required: true
          schema:
            type: string
        - name: resource
          in: header
          description: Indicates the resource to access
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token_response'
  /TokenAvailability:
    get:
      summary: Availability
      description: Checks Token API Availability
      operationId: availability
      responses:
        '200':
          description: 
components:
  schemas:
    Token_response:
      type: object
      properties:
        token_type:
          type: string
        expires_in:
          type: string
        ext_expires_in:
          type: string
        expires_on:
          type: string
        not_before:
          type: string
        resource:
          type: string
        access_token:
          type: string
      x-apim-schema-name: Token response