openapi: 3.0.1
info:
  title: Bank Interfaces
  description: >-
    This describes the two main interfaces where Clickatell and a bank interact with one another when dealing with a purchase.
  version: "2.0"
servers:
  - url: "https://client_server_hostname/"
    variables: {}
paths:
  /reserveFunds:
    post:
      tags:
        - Bank Interfaces
      summary: Reserve funds endpoint implemented by bank
      description: >-
        The  reserveFunds  API  is  the  first  point  of  communication  between Clickatell and  the  bank,  where Clickatell requests the  reservation  of  funds  for  a  purchase  from the client, and the bank replies with the outcome of this reservation </br></br>
        <a href="https://docs.clickatell.com/payments/transact/signature-checksum-calculation">Signature Checksum Calculation</a>
      operationId: Reserve Funds
      parameters:
        - name: Signature
          in: header
          description: This is an "optional" hash calculated using a shared secret between Clickatell and the client
          required: false
          schema: 
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReserveFundsRequest"
        required: true
      responses:
        "200":
          description: successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessDetails"
  /transactResult:
    post:
      tags:
        - Bank Interfaces
      summary: Endpoint that informs the client of the outcome of a transaction
      description: >-
        The transactResult API is the second point of interaction between Clickatell and the bank, where Clickatell confirms the outcome of the dispensing of the product with the bank, and the bank can either proceed with the payment or cancel the fund reservation </br>
        <a href="https://docs.clickatell.com/payments/transact/signature-checksum-calculation">Signature Checksum Calculation</a>
      operationId: Transact Result
      parameters:
        - name: Signature
          in: header
          description: This is a hash calculated using a shared secret between Clickatell and the client
          required: false
          schema: 
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactResultRequest"
        required: true
      responses:
        "200":
          description: successful response
components:
  schemas:
    ReserveFundsRequest:
      required:
        - clientTxnRef
        - raasTxnRef
        - productId
        - productTypeId
        - purchaseAmount
        - reserveAmount
        - feeAmount
        - clientShareAmount
        - settlementAmount
        - sourceIdentifier
        - targetIdentifier
        - channelId
        - channelName
        - timestamp
      type: object
      properties:
        clientTxnRef:
          maxLength: 64
          type: string
          description: >-
            Unique client reference to the transaction
          example: "seo8w3-3wsf8cffdd34-f58l"
        raasTxnRef:
          maxLength: 64
          type: string
          description: Unique Clickatell reference to the transaction
          example: "ffdd34-3wsf8c-seo8w3-f58l"
        productId:
          maxLength: 5
          type: integer
          description: ID of the product requested to be purchased. A list of products will be supplied by Clickatell
          example: 110
        productType:
          maxLength: 32
          type: integer
          description: Unique reference to the product type (classification, group or line) that was purchased, for instance pre-purchased airtime or data
          example: 3
        purchaseAmount:
          maxLength: 12
          type: integer
          description: >-
            The value of the SKU that the customer wishes to receive, in the lowest
            denomination (e.g. cents or pennies), for instance, $250.00 would equate
            to the value 25000. This amount excludes the fee amount charged for
            the product
          example: 10000
        reserveAmount:
          maxLength: 12
          type: integer
          description: >- 
            The   amount   to   be   reserved   by   the   funding source. Typically, the same as the TPV (Total Purchase Value). In  the  lowest  denomination  (e.g.  cents or  pennies),  for instance  $250.00  would  equate to the value 25000. May differ from the purchase amount and vend amount if a fee   has   been   added   on top   of  the  purchase amount.
          example: 110  
        feeAmount:
          maxLength: 12
          type: integer
          description: >-
            A fixed transaction fee that Clickatell charges on top of the requested purchase value of a product. 
            Please note a zero amount needs to be specified if there is no fee applicable. If the fee amount is not correct the request validation will fail
          format: int32
          example: 0
        clientShareAmount:
          maxLength: 12
          type: integer
          description: The  portion  of  the  TPV due  to  the  client,  stated as  an  amount.  In  the  lowest  denomination  (e.g. cents  or  pennies),  for  instance  $250.00  would equate to the value 25000
          example: 487
        settlementAmount:
          maxLength: 12
          type: integer
          description: The amount settled to Clickatell by the client. In the lowest denomination (e.g. cents or pennies), for  instance  $250.00  would  equate  to  the  value 25000
          example: 14513
        sourceIdentifier:
          maxLength: 32
          type: string
          description: >-
            The  unique  identifier  for  the source,  as  recognized  by the 
            bank.  This  is  typically  the  mobile  phone  number (MSISDN)   
            but    can    be    another    unique    identifier recognized by
            the bank.
          example: "2341234567899"
        targetIdentifier:
          maxLength: 32
          type: string
          description: >-
            The unique identifier for the intended recipient (or target/destination) of the product being purchased. This may be the buyer (“Self”) or someone else (a so-called “3rd party purchase”)
          example: "2348012345555"  
        channelId:
          maxLength: 2
          type: integer
          description: The channel is the user interface, platform or service that the buyer used to initiate a purchase from
          example: 7
          format: int32
        channelName:
          maxLength: 64
          type: string
          description: >-
            This is the specific name of the channel used to initiate a purchase
          example: "USSD"
        channelSessionId:
          maxLength: 64
          type: string
          description: >-
            This is a unique reference to the channel-specific engagement when the purchase was initiated (for example USSD Session ID, if the purchase was over USSD)
          example: "144974973281"
        authCode:
          maxLength: 64
          type: string
          description: >-
            An authentication code provided by the buyer that the bank can use to
            verify the buyer’s identity. Used in the reserveFunds request if supplied
          example: 1234
        timestamp:
          maxLength: 32
          type: string
          format: date-time
          description: >-
            The timestamp of when an API request or response was sent, in ISO-8601 format
          example: "2017-06-29T16:39:42.735Z"
        accountIdentifier:
          type: string
          maxLength: 64
          description: The account that will be deducted from. Only mandatory if there is no concept of a default account for the buyer at the funding source
          example: "3745******0762"
    SuccessDetails:
      required:
        - responseCode
        - reserveFundsTxnRef
      type: object
      properties:
        responseCode:
          maxLength: 4
          type: string
          description: The response code used on the reserveFunds Response indicates the result of attempting to reserve funds on a buyer’s account <br> 0000 Success <br>2010 Insufficient funds<br> 2020 Invalid authentication code or unknown 'sourceIdentifier'<br> 2030 Account not mapped <br>2040 Maximum amount exceeded <br>2050 Below minimum amount <br>2060 Internal time out<br> 2070 'sourceIdentifier' blacklisted <br>2080 Account inactive<br> 2090 Unknown error
          example: "0000"
        reserveFundsTxnRef:
          maxLength: 64
          type: string
          description: This  is  the  universally  unique  identifier  that  the bank must generate when it reserves funds on a buyer’s account
          example: "ffdd34-3wsf8c-seo8w3-f58l"
    TransactResultRequest:
      required:
        - clientTxnRef
        - raasTxnRef
        - reserveFundsTxnRef
        - responseCode
        - reserveAmount
        - feeAmount
        - clientShareAmount
        - settlementAmount
        - timestamp
        - token
      type: object
      properties:
        clientTxnRef:
          maxLength: 64
          type: string
          description: >-
            Unique client reference to the transaction
          example: "seo8w3-3wsf8cffdd34-f58l"
        raasTxnRef:
          maxLength: 64
          type: string
          description: Unique Clickatell reference to the transaction
          example: "ffdd34-3wsf8c-seo8w3-f58l"
        reserveFundsTxnRef:
          maxLength: 64
          type: string
          description: This  is  the  universally  unique  identifier  that  the bank must generate when it reserves funds on a buyer’s account
          example: "f58l-3wsf8c-seo8w3-ffdd34"
        responseCode:
          maxLength: 4
          type: integer
          description: The  response  code used  on  the  reserveFunds Response  indicates  the  result  of  attempting  to reserve funds on a buyer’s account. Note  that  all  response  codes  other  than  0000 will be treated as a failed funds reservation (and consequently,not  followed  by  a  Transact  Result confirmation)
          example: 0000
        reserveAmount:
          maxLength: 12
          type: integer
          description: >- 
            The   amount   to   be   reserved   by   the   funding source. In  the  lowest  denomination  (e.g.  cents or  pennies),  for instance  $250.00  would  equate to the value 25000. Typically,the same as the TPV (Total Purchase Value). May differ from the purchase amount and vend amount if a fee   has   been   added   on top   of  the  purchase amount.  
          example: 110  
        feeAmount:
          maxLength: 12
          type: integer
          description: >-
            A fixed transaction fee that Clickatell charges on top of the requested purchase value of a product. 
            Please Note a zero amount needs to be specified if there is no fee applicable. If the fee amount is not correct the request validation willfail
          format: int32
          example: 0
        clientShareAmount:
          maxLength: 12
          type: integer
          description: The  portion  of  the  TPV due  to  the  client,  stated as  an  amount.  In  the  lowest  denomination  (e.g. cents  or  pennies),  for  instance  $250.00  would equate to the value 25000
          example: 487
        settlementAmount:
          maxLength: 12
          type: integer
          description: The amount settled to Clickatell by the Client. In the lowest denomination (e.g. cents or pennies), for  instance  $250.00  would  equate  to  the  value 25000
          example: 14513
        timestamp:
          maxLength: 32
          type: string
          format: date-time
          description: >-
            The timestamp of when an API request or response was sent, in ISO-8601 format
          example: "2017-06-29T16:39:42.735Z"
        token:
          type: string
          maxLength: 60
          description: Some product types return a recharge PIN/Token which consumers use to redeem the value of the purchase  (e.g.  PIN/Token  entered  in  a  Pre-Paid meter). The Clickatell platform will deliver this PIN/Token to the consumer via SMS.The  PIN/Token  will  only  be returned  via  the  API when  the  Clients/Funding  sources  are  configured on the Clickatell platform to receive it
          example: "XYZ"
