---
swagger: "2.0"
info:
  description: "Shipment Status API allows developer to request for latest shipment's information."
  version: "1.0.2"
  title: "DGF Shipment Status API"
host: "api.dhl.com"
basePath: "/dgff/transportation"
schemes:
- "https"
produces:
- "application/json"
security:
  - apiKey: []
paths:
  /shipment-status:
    get:
      operationId: "ShipmentStatus_GET"
      summary: /shipment-status      
      produces:
      - "application/json"
      parameters:
      - name: "housebill"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/ShipmentStatus_GET_response"
        401:
          description: "Access Denied"
        500:
          description: "Internal Server Error"
        404:
          description: "Shipment Not Found"
  /housebill-numbers:
    get:
      operationId: "HousebillNumber_GET"
      summary: /housebill-numbers      
      description: "GET housebill number(s) using references like customer's reference, container number or masterbill number. Housebill number(s) returned by the response could be used to get shipment-tracking information"
      parameters:
      - name: "search-type"
        in: "query"
        required: true
        type: "string"
        description: "Specifiy one of the supported search-types"
        enum: [customer-reference, masterbill, container-number]
      - name: "value"
        in: "query"
        required: true
        type: "string"
        description: "Search string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/HousebillNumbers_GET_response"
        401:
          description: "Access Denied"
        500:
          description: "Internal Server Error"
securityDefinitions:
  apiKey:
    type: apiKey
    name: DHL-API-Key
    in: header
definitions:
  ShipmentStatus_GET_response:
    required:
    - "ShipmentStatus"
    properties:
      ShipmentStatus:
        $ref: "#/definitions/ShipmentStatus"
  ShipmentStatus:
    required:
    - "MessageHeader"
    - "Shipment"
    properties:
      Shipment:
        $ref: "#/definitions/Shipment"
      MessageHeader:
        $ref: "#/definitions/MessageHeader"
  Origin:
    required:
    - "LocationCode"
    properties:
      LocationCode:
        type: "string"
        minLength: 3
        maxLength: 5
        description: "Origin location code in IATA or three-character DHL station code format."
        example: "SIN"
      LocationCodeUN:
        type: "string"
        minLength: 5
        maxLength: 5
        description: "Origin location code in UNLOCODE or five-character DHL station code format."
        example: "SGSIN"
      LocationName:
        type: "string"
        maxLength: 50
        description: "Origin location name."
        example: "Singapore"
      CountryCode:
        type: "string"
        description: "Origin ISO country code."
        example: "SG"
  TotalVolume:
    required:
    - "@uom"
    properties:
      '*body':
        type: "string"
        description: "Total Shipment volume."
        example: "0.337"
      '@uom':
        type: "string"
        minLength: 1
        maxLength: 3
        description: "Total Shipment volume uom - default to MTQ (cubic meters)."
        example: "MTQ"
  Timestamp:
    required:
    - "TimestampDateTime"
    - "TimestampDescription"
    properties:
      TimestampCode:
        type: "string"
      TimestampDateTime:
        type: "string"
      TimestampText:
        type: "string"
      TimestampDescription:
        type: "string"
  MessageHeader:
    required:
    - "CreationDateTime"
    - "MessageID"
    - "Version"
    properties:
      ReceiverID:
        type: "string"
      CreationDateTime:
        type: "string"
      Version:
        type: "string"
      SenderID:
        type: "string"
      MessageID:
        type: "string"
  TotalWeight:
    required:
    - "@uom"
    properties:
      '*body':
        type: "string"
        description: "Total Shipment weight."
        example: "85.0"
      '@uom':
        type: "string"
        minLength: 1
        maxLength: 3
        description: "Total Shipment weight uom - default to KGM (kilograms)."
        example: "KGM"
  Destination:
    required:
    - "LocationCodeUN"
    properties:
      LocationCode:
        type: "string"
        minLength: 3
        maxLength: 3
        description: "Destination location code in IATA or three-character DHL station code format."
        example: "LAX"
      LocationCodeUN:
        type: "string"
        minLength: 5
        maxLength: 5
        description: "Destination location code in UNLOCODE or five-character DHL station code format."
        example: "USLAX"
      LocationName:
        type: "string"
        maxLength: 50
        description: "Destination location name."
        example: "Los Angeles"
      CountryCode:
        type: "string"
        description: "Destination ISO country code."
        example: "US"
  Shipment:
    required:
    - "Destination"
    - "HousebillNumber"
    - "Origin"
    - "ProductType"
    - "Timestamp"
    properties:
      Origin:
        $ref: "#/definitions/Origin"
      Destination:
        $ref: "#/definitions/Destination"
      TotalWeight:
        $ref: "#/definitions/TotalWeight"
      TotalPackages:
        type: "string"
        description: "Total number of packages."
        example: "1"
      HousebillNumber:
        type: "string"
        maxLength: 35
        description: "Housebill Number"
        example: "Q317839"
      HouseFileNumber:
        type: "string"
        maxLength: 35
        description: "Internal Housebill Number. Applicable to Air where HousebillNumber format is XXX-XX-9999999."
        example: "Z997710"
      ProductType:
        type: "string"
        maxLength: 10
        description: "Product Type with possible values of:\n - AIR\n - OCEAN (includes ROAD)\n - USDOMESTIC"
        example: "AIR"
      TotalVolume:
        $ref: "#/definitions/TotalVolume"
      Timestamp:
        $ref: "#/definitions/Timestamp"
  HousebillNumbers_GET_response:
    required:
    - "housebill-numbers"
    properties:
      housebill-numbers:
        type: "array"
        items:
          type: "string"
        example: [SCLA00055,SCLA00056,SCLA00057]